import * as ast from "go/ast";
import * as token from "go/token";
import * as types from "go/types";
import { defineAnalyzer, formatNode, type Pass } from "tsk";
import { inspect } from "tsk/passes";

interface Config {
  /** Skip files generated by tools with these names, besides protoc's. */
  skipGeneratedBy: string[];
  /** Skip files whose path or name matches one of these globs. */
  skipFiles: string[];
  /** Skip every generated file. */
  skipAnyGenerated: boolean;
  /** Also check the first argument of append. */
  replaceFirstArgInAppend: boolean;
}

const nodeTypes = [
  ast.AssignStmt,
  ast.BinaryExpr,
  ast.CallExpr,
  ast.SelectorExpr,
  ast.StarExpr,
  ast.IncDecStmt,
  ast.UnaryExpr,
  ast.KeyValueExpr,
  ast.DeclStmt,
  ast.ReturnStmt,
];

export default defineAnalyzer<Config>({
  name: "protogetter",
  doc: "Reports direct reads from proto message fields when getters should be used",
  requires: [inspect],
  config: { skipGeneratedBy: [], skipFiles: [], skipAnyGenerated: false, replaceFirstArgInAppend: false },
  run(pass) {
    const generators = ["protoc-gen-go", "protoc-gen-go-grpc", "protoc-gen-grpc-gateway", ...pass.config.skipGeneratedBy.map((s) => s.trim())].filter(
      (s) => s !== "",
    );
    const globs = pass.config.skipFiles
      .map((s) => s.trim())
      .filter((s) => s !== "")
      .map(globToRegExp);
    const filter = new PosFilter(pass);
    for (const fileCursor of pass.resultOf(inspect).root().children()) {
      const file = fileCursor.node() as ast.File;
      const filename = pass.fset.position(file.pos()).filename;
      const basename = filename.slice(filename.lastIndexOf("/") + 1);
      if (isSkippedGenerated(file, generators, pass.config.skipAnyGenerated) || globs.some((glob) => glob.test(filename) || glob.test(basename))) {
        continue;
      }
      for (const cursor of fileCursor.preorder(...nodeTypes)) {
        analyse(pass, filter, cursor.node()!);
      }
    }
  },
});

function analyse(pass: Pass<Config>, filter: PosFilter, node: ast.Node): void {
  if (filter.isFiltered(node.pos())) {
    return;
  }
  const processor = new Processor(pass, filter);
  const result = processor.process(node);
  if (processor.error !== null) {
    pass.report({ pos: node.pos(), end: node.end(), message: `error: ${processor.error}` });
    return;
  }
  // Processing may filter the node itself, as for an assignment's target.
  if (result === null || filter.isFiltered(node.pos()) || result.from === result.to) {
    return;
  }
  if (filter.isAlreadyReplaced(node.pos(), node.end())) {
    return;
  }
  filter.addAlreadyReplaced(node.pos(), node.end());
  const message = `avoid direct access to proto field ${result.from}, use ${result.to} instead`;
  pass.report({
    pos: node.pos(),
    end: node.end(),
    message,
    suggestedFixes: [{ message, textEdits: [{ pos: node.pos(), end: node.end(), newText: result.to }] }],
  });
}

// PosFilter records positions not to report, such as fields being written,
// and the source ranges already replaced on each line.
class PosFilter {
  private readonly positions = new Set<token.Pos>();
  private readonly replaced = new Map<string, Map<number, [number, number]>>();

  constructor(private readonly pass: Pass<Config>) {}

  isFiltered(pos: token.Pos): boolean {
    return this.positions.has(pos);
  }

  add(pos: token.Pos): void {
    this.positions.add(pos);
  }

  isAlreadyReplaced(pos: token.Pos, end: token.Pos): boolean {
    const start = this.pass.fset.position(pos);
    const range = this.replaced.get(start.filename)?.get(start.line);
    return range !== undefined && range[0] <= start.offset && this.pass.fset.position(end).offset <= range[1];
  }

  addAlreadyReplaced(pos: token.Pos, end: token.Pos): void {
    const start = this.pass.fset.position(pos);
    const endOffset = this.pass.fset.position(end).offset;
    let lines = this.replaced.get(start.filename);
    if (lines === undefined) {
      lines = new Map();
      this.replaced.set(start.filename, lines);
    }
    const range = lines.get(start.line);
    if (range === undefined || range[0] > start.offset || endOffset > range[1]) {
      lines.set(start.line, [start.offset, endOffset]);
    }
  }
}

// Processor builds the source of an expression as written (from) and with
// getters (to), filtering positions that must not use getters.
class Processor {
  error: string | null = null;
  private to = "";
  private from = "";

  constructor(
    private readonly pass: Pass<Config>,
    private readonly filter: PosFilter,
  ) {}

  process(node: ast.Node): { from: string; to: string } | null {
    switch (node.$type) {
      case "AssignStmt":
        // Assignments write fields rather than read them.
        node.lhs.forEach((lhs, i) => {
          this.filter.add(lhs!.pos());
          if (lhs!.$type === "StarExpr") {
            this.filter.add(lhs!.x!.pos());
          }
          const value = node.rhs[i];
          if (value?.$type === "SelectorExpr" && this.hasPointerKeyWithoutPointerGetter(lhs!, value)) {
            this.filter.add(value.sel!.pos());
          }
        });
        break;
      case "IncDecStmt":
        this.filter.add(node.x!.pos());
        break;
      case "UnaryExpr":
        // Taking a field's address most likely writes through it, as for sql.Scan.
        if (node.op === token.AND) {
          this.filter.add(node.x!.pos());
        }
        break;
      case "KeyValueExpr":
        if (node.value?.$type === "SelectorExpr" && this.hasPointerKeyWithoutPointerGetter(node.key!, node.value)) {
          this.filter.add(node.value.sel!.pos());
        }
        break;
      case "CallExpr":
        return this.processCall(node);
      case "SelectorExpr":
        if (!this.isProtoMessage(node.x!)) {
          return null;
        }
        this.processInner(node);
        break;
      case "StarExpr": {
        const field = node.x;
        if (field?.$type !== "SelectorExpr" || !this.isProtoMessage(field.x!)) {
          return null;
        }
        // proto2 fields are pointers; the fix drops the dereference.
        this.from += "*";
        this.processInner(field);
        break;
      }
      case "BinaryExpr":
        this.processNilComparison(node);
        return null;
      case "DeclStmt":
        if (node.decl?.$type === "GenDecl") {
          for (const spec of node.decl.specs) {
            if (spec?.$type === "ValueSpec" && spec.type?.$type === "StarExpr") {
              for (const value of spec.values) {
                this.filter.add(value!.pos());
              }
            }
          }
        }
        break;
      case "ReturnStmt":
        this.filterOptionalProtoSelectors(node.results as ast.Expr[]);
        break;
    }
    return { from: this.from, to: this.to };
  }

  private processCall(call: ast.CallExpr): { from: string; to: string } | null {
    const fun = call.fun;
    if (!this.pass.config.replaceFirstArgInAppend && call.args.length > 0 && fun?.$type === "Ident" && fun.name === "append") {
      this.filter.add(call.args[0]!.pos());
      return { from: this.from, to: this.to };
    }
    if (fun?.$type === "Ident") {
      // Optional fields may be passed to local functions without a getter.
      const decl = fun.obj?.decl as ast.Node | null | undefined;
      if (call.args.length === 0 || fun.obj?.kind !== ast.Fun || decl?.$type !== "FuncDecl" || decl.type === null) {
        return null;
      }
      this.filterOptionalProtoSelectors(call.args as ast.Expr[]);
    } else if (fun?.$type === "SelectorExpr") {
      this.filterOptionalProtoSelectors(call.args as ast.Expr[]);
      if (!this.isProtoMessage(fun.x!)) {
        return null;
      }
      this.processInner(call);
    } else {
      return null;
    }
    return { from: this.from, to: this.to };
  }

  // processNilComparison filters "msg.Field == nil" when the getter does not
  // return a pointer, since the getter's zero value could never be nil.
  private processNilComparison(expr: ast.BinaryExpr): void {
    if (expr.op !== token.EQL && expr.op !== token.NEQ) {
      return;
    }
    const isNil = (e: ast.Expr | null) => e?.$type === "Ident" && e.name === "nil";
    const xIsNil = isNil(expr.x);
    if (!xIsNil && !isNil(expr.y)) {
      return;
    }
    const operand = xIsNil ? expr.y : expr.x;
    if (operand?.$type !== "SelectorExpr" || !this.isProtoMessage(operand.x!)) {
      return;
    }
    const [hasPointer, ok] = this.getterResultHasPointer(operand.x!, operand.sel!.name);
    if (ok && !hasPointer) {
      this.filter.add(expr.x!.pos());
    }
  }

  private filterOptionalProtoSelectors(args: ast.Expr[]): void {
    for (const arg of args) {
      if (arg.$type === "SelectorExpr" && this.isProtoMessage(arg.x!) && this.isOptionalProto(arg)) {
        this.filter.add(arg.sel!.pos());
      }
    }
  }

  private processInner(expr: ast.Expr): void {
    switch (expr.$type) {
      case "Ident":
        this.write(expr.name);
        break;
      case "BasicLit":
        this.write(expr.value);
        break;
      case "UnaryExpr":
        if (expr.op === token.AND) {
          this.write(formatNode(expr));
          return;
        }
        this.write(token.Token.string(expr.op));
        this.processInner(expr.x!);
        break;
      case "SelectorExpr": {
        this.processInner(expr.x!);
        this.write(".");
        const name = expr.sel!.name;
        if (this.methodExists(expr.x!, `Get${name}`) && !this.filter.isFiltered(expr.sel!.pos()) && this.isProtoMessage(expr.x!)) {
          this.from += name;
          this.to += `Get${name}()`;
          return;
        }
        this.write(name);
        break;
      }
      case "CallExpr":
        this.processInner(expr.fun!);
        this.write("(");
        expr.args.forEach((arg, i) => {
          if (i > 0) {
            this.write(",");
          }
          this.processInner(arg!);
        });
        this.write(")");
        break;
      case "IndexExpr":
        this.processInner(expr.x!);
        this.write("[");
        this.processInner(expr.index!);
        this.write("]");
        break;
      case "BinaryExpr":
        this.processInner(expr.x!);
        this.write(token.Token.string(expr.op));
        this.processInner(expr.y!);
        break;
      case "ParenExpr":
        this.write("(");
        this.processInner(expr.x!);
        this.write(")");
        break;
      case "StarExpr":
        this.write("*");
        this.processInner(expr.x!);
        break;
      case "CompositeLit":
      case "TypeAssertExpr":
      case "ArrayType":
      case "FuncLit":
      case "SliceExpr":
      case "MapType":
        this.write(formatNode(expr));
        break;
      default:
        this.error = `processInner: not implemented for type: *ast.${expr.$type}`;
    }
  }

  private write(s: string): void {
    this.to += s;
    this.from += s;
  }

  // isProtoMessage reports whether an expression is a generated protobuf
  // message, skipping gogo messages whose getters may not check for nil.
  private isProtoMessage(expr: ast.Expr): boolean {
    if (this.methodExists(expr, "ProtoReflect")) {
      return true;
    }
    return this.methodExists(expr, "ProtoMessage") && !this.methodExists(expr, "MarshalToSizedBuffer");
  }

  private isOptionalProto(sel: ast.SelectorExpr): boolean {
    if (this.pass.typesInfo.typeOf(sel)?.underlying()?.$type !== "Pointer") {
      return false;
    }
    return !this.getterResultHasPointer(sel.x!, sel.sel!.name)[0];
  }

  private methodExists(expr: ast.Expr, name: string): boolean {
    const named = this.namedType(expr);
    return named !== null && this.methods(named).some((method) => method!.name() === name);
  }

  // getterResultHasPointer reports whether the getter for a field returns a
  // pointer, and whether such a getter exists.
  private getterResultHasPointer(expr: ast.Expr, name: string): [boolean, boolean] {
    const named = this.namedType(expr);
    const getter = named === null ? undefined : this.methods(named).find((method) => method!.name() === `Get${name}`);
    const sig = getter?.type();
    if (sig?.$type !== "Signature" || sig.results()!.len() === 0) {
      return [false, false];
    }
    return [sig.results()!.at(0)!.type()?.$type === "Pointer", true];
  }

  private hasPointerKeyWithoutPointerGetter(key: ast.Expr, value: ast.SelectorExpr): boolean {
    if (this.pass.typesInfo.typeOf(key)?.$type !== "Pointer") {
      return false;
    }
    const [hasPointer, ok] = this.getterResultHasPointer(value.x!, value.sel!.name);
    return ok && !hasPointer;
  }

  private namedType(expr: ast.Expr): types.Named | null {
    let t = this.pass.typesInfo.typeOf(expr);
    const u = t?.underlying();
    if (u?.$type === "Pointer") {
      t = u.elem();
    }
    const named = types.unalias(t);
    return named?.$type === "Named" ? named : null;
  }

  private methods(named: types.Named): (types.Func | null)[] {
    return [...Array(named.numMethods()).keys()].map((i) => named.method(i));
  }
}

// isSkippedGenerated reports whether a file was generated by one of the
// generators, or is generated at all when skipAny is set.
function isSkippedGenerated(file: ast.File, generators: string[], skipAny: boolean): boolean {
  if (file.comments.length === 0) {
    return false;
  }
  if (skipAny && ast.isGenerated(file)) {
    return true;
  }
  const first = file.comments[0]!.text();
  return generators.some((generator) => first.startsWith(`Code generated by ${generator}`));
}

// globToRegExp compiles a gobwas/glob pattern without separators, so * and ?
// also match /.
function globToRegExp(glob: string): RegExp {
  let source = "";
  for (let i = 0; i < glob.length; i++) {
    const char = glob[i];
    if (char === "*") {
      source += ".*";
    } else if (char === "?") {
      source += ".";
    } else if (char === "[") {
      const end = glob.indexOf("]", i);
      const body = glob.slice(i + 1, end);
      source += `[${body.startsWith("!") ? `^${body.slice(1)}` : body}]`;
      i = end;
    } else if (char === "{") {
      source += "(?:";
    } else if (char === "}") {
      source += ")";
    } else if (char === ",") {
      source += source.lastIndexOf("(?:") > source.lastIndexOf(")") ? "|" : ",";
    } else if (char === "\\") {
      source += (glob[++i] ?? "").replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");
    } else {
      source += char.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");
    }
  }
  return new RegExp(`^${source}$`);
}
