package bindgen

import (
	"go/types"
	"slices"
	"strconv"
	"strings"

	"github.com/alecthomas/errors"
	. "github.com/alecthomas/types/optional"

	"github.com/alecthomas/tsktsk/internal/naming"
)

type declarer struct {
	model *model
	pkg   *types.Package
	out   strings.Builder
}

func newDeclarer(m *model, pkg *types.Package) *declarer {
	return &declarer{model: m, pkg: pkg}
}

// render declares the package as an ambient TypeScript module that imports
// the other exposed packages by name.
func (d *declarer) render(exposed []*types.Package) ([]byte, error) {
	d.line("// Code generated by tsk-gen. DO NOT EDIT.")
	d.line("")
	d.line("declare module " + strconv.Quote(d.pkg.Path()) + " {")
	d.line(`  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";`)
	for _, other := range exposed {
		if other != d.pkg {
			d.line("  import type * as " + other.Name() + " from " + strconv.Quote(other.Path()) + ";")
		}
	}
	for _, object := range d.model.members(d.pkg) {
		if err := d.member(object); err != nil {
			return nil, errors.Wrapf(err, "%s.%s", d.pkg.Path(), object.Name())
		}
	}
	d.line("}")
	return []byte(d.out.String()), nil
}

func (d *declarer) line(text string) {
	d.out.WriteString(text + "\n")
}

func (d *declarer) member(object types.Object) error {
	switch object := object.(type) {
	case *types.Func:
		d.line("  export function " + naming.Function(object.Name()) + d.signature(object.Signature()) + ";")
	case *types.Var:
		if isErrorVar(object) {
			// The runtime throws Go errors as exceptions; an error variable is
			// the class matching errors that errors.Is would match.
			d.line("  export class " + object.Name() + " extends GoError {")
			d.line("    private constructor();")
			d.line("  }")
			return nil
		}
		d.line("  export const " + object.Name() + ": " + d.tsType(object.Type()) + ";")
	case *types.Const:
		d.line("  export const " + object.Name() + ": " + d.tsType(object.Type()) + ";")
	case *types.TypeName:
		return d.typeName(object)
	}
	return nil
}

func (d *declarer) typeName(object *types.TypeName) error {
	named, ok := object.Type().(*types.Named)
	if !ok {
		// An exported alias names a type declared elsewhere.
		d.line("  export type " + object.Name() + " = " + d.tsType(types.Unalias(object.Type())) + ";")
		return nil
	}
	if isErrorType(object) {
		return d.errorType(object, named)
	}
	switch underlying := named.Underlying().(type) {
	case *types.Struct:
		return d.structType(object, named, underlying)
	case *types.Interface:
		return d.interfaceType(object, underlying)
	case *types.Basic:
		d.line("  export type " + object.Name() + " = " + d.tsType(underlying) + ";")
		d.receiverFunctions(object, named)
	default:
		d.line("  export type " + object.Name() + " = " + d.tsType(underlying) + ";")
	}
	return nil
}

// structType declares the fields and methods of T and *T, plus a type token
// standing for a typed nil, as Go uses with inspector.Preorder.
func (d *declarer) structType(object *types.TypeName, named *types.Named, structure *types.Struct) error {
	d.line("  export interface " + object.Name() + " {")
	if err := d.members(object, named, Some(structure), map[string]bool{}); err != nil {
		return err
	}
	d.line("  }")
	d.line("  export const " + object.Name() + ": TypeToken<" + object.Name() + ">;")
	return nil
}

// errorType declares an error type as a GoError subclass, so instanceof
// narrows a caught exception. Error's own members are reserved. Slices and
// arrays also expose their elements, as Go code ranges over them.
func (d *declarer) errorType(object *types.TypeName, named *types.Named) error {
	d.line("  export class " + object.Name() + " extends GoError {")
	d.line("    private constructor();")
	reserved := map[string]bool{"message": true, "name": true, "stack": true, "cause": true}
	structure := None[*types.Struct]()
	switch underlying := named.Underlying().(type) {
	case *types.Struct:
		structure = Some(underlying)
	case *types.Slice, *types.Array:
		element := wrapUnion(d.tsType(underlying.(interface{ Elem() types.Type }).Elem()))
		d.line("    readonly length: number;")
		d.line("    at(index: number): " + element + ";")
		d.line("    [Symbol.iterator](): Iterator<" + element + ">;")
		reserved["length"], reserved["at"] = true, true
	case *types.Map:
		return errors.Errorf("error type %s is a map, which has no class form", object.Name())
	}
	if err := d.members(object, named, structure, reserved); err != nil {
		return err
	}
	d.line("  }")
	return nil
}

// members declares $type, a struct's fields, and the methods of T and *T.
func (d *declarer) members(object *types.TypeName, named *types.Named, structure Option[*types.Struct], names map[string]bool) error {
	names["$type"] = true
	d.line("    readonly $type: " + strconv.Quote(object.Name()) + ";")
	if structure, ok := structure.Get(); ok {
		for _, field := range promotedFields(structure) {
			name := naming.Member(field.Name())
			if names[name] {
				return errors.Errorf("field %s collides with another member", field.Name())
			}
			names[name] = true
			d.line("    readonly " + name + ": " + d.tsType(field.Type()) + ";")
		}
	}
	for selection := range types.NewMethodSet(types.NewPointer(named)).Methods() {
		method := selection.Obj().(*types.Func)
		if !method.Exported() || method.Signature().TypeParams().Len() > 0 {
			continue
		}
		name := naming.Member(method.Name())
		if names[name] {
			return errors.Errorf("method %s collides with another member", method.Name())
		}
		names[name] = true
		d.line("    " + name + d.signature(method.Signature()) + ";")
	}
	return nil
}

// promotedFields returns exported fields, including those promoted from
// embedded structs, shallowest first so shadowing follows Go's rules.
func promotedFields(structure *types.Struct) []*types.Var {
	var fields []*types.Var
	seen := map[string]bool{}
	level := []*types.Struct{structure}
	for len(level) > 0 {
		var next []*types.Struct
		for _, current := range level {
			for field := range current.Fields() {
				if field.Embedded() {
					if embedded, ok := embeddedStruct(field.Type()); ok {
						next = append(next, embedded)
					}
				}
				if !field.Exported() || seen[field.Name()] {
					continue
				}
				seen[field.Name()] = true
				fields = append(fields, field)
			}
		}
		level = next
	}
	return fields
}

func embeddedStruct(t types.Type) (*types.Struct, bool) {
	if pointer, ok := t.(*types.Pointer); ok {
		t = pointer.Elem()
	}
	structure, ok := t.Underlying().(*types.Struct)
	return structure, ok
}

// interfaceType declares a union of the implementing types when every
// implementation is exposed, so scripts can narrow on $type. Otherwise it
// declares the interface's methods.
func (d *declarer) interfaceType(object *types.TypeName, iface *types.Interface) error {
	if implementers, ok := d.model.implementers(object.Pkg(), iface); ok {
		d.line("  export type " + object.Name() + " = " + strings.Join(implementers(d), " | ") + ";")
		return nil
	}
	d.line("  export interface " + object.Name() + " {")
	d.line("    readonly $type: string;")
	for method := range iface.Methods() {
		if method.Exported() {
			d.line("    " + naming.Member(method.Name()) + d.signature(method.Signature()) + ";")
		}
	}
	d.line("  }")
	return nil
}

// receiverFunctions exposes the methods of a basic type, such as token.Token,
// as functions taking the receiver first, because scripts see a plain number
// or string.
func (d *declarer) receiverFunctions(object *types.TypeName, named *types.Named) {
	var functions []string
	for selection := range types.NewMethodSet(named).Methods() {
		method := selection.Obj().(*types.Func)
		if !method.Exported() {
			continue
		}
		signature := method.Signature()
		parameters := append([]*types.Var{types.NewParam(0, nil, "receiver", named)}, slices.Collect(signature.Params().Variables())...)
		withReceiver := types.NewSignatureType(nil, nil, nil, types.NewTuple(parameters...), signature.Results(), signature.Variadic())
		functions = append(functions, naming.Member(method.Name())+d.signature(withReceiver))
	}
	if len(functions) == 0 {
		return
	}
	d.line("  export const " + object.Name() + ": {")
	for _, function := range functions {
		d.line("    " + function + ";")
	}
	d.line("  };")
}

// hiddenImplementers are unexported types that implement an exposed interface
// but never reach callers. go/types.Scope resolves lazyObject before returning
// it, so types.Object stays a closed union.
func hiddenImplementers() []string {
	return []string{"go/types.lazyObject"}
}

func embeds(structure *types.Struct, base *types.TypeName) bool {
	for field := range structure.Fields() {
		if !field.Embedded() {
			continue
		}
		embedded := types.Unalias(field.Type())
		if pointer, ok := embedded.(*types.Pointer); ok {
			embedded = pointer.Elem()
		}
		if named, ok := embedded.(*types.Named); ok && named.Obj() == base {
			return true
		}
	}
	return false
}

// reference names an exposed type from the current module.
func (d *declarer) reference(object *types.TypeName) string {
	if object.Pkg() == d.pkg {
		return object.Name()
	}
	return object.Pkg().Name() + "." + object.Name()
}

// tsType renders the TypeScript type scripts see for a Go value. Pointers,
// interfaces, and functions may be nil, so they include null. Slices never do
// because the runtime converts nil slices to empty arrays.
func (d *declarer) tsType(t types.Type) string {
	switch t := types.Unalias(t).(type) {
	case *types.Basic:
		return basicType(t)
	case *types.Named:
		return d.namedType(t)
	case *types.Pointer:
		named, ok := types.Unalias(t.Elem()).(*types.Named)
		if ok && d.isExposed(named) {
			return d.reference(named.Obj()) + " | null"
		}
		return unknownType
	case *types.Slice:
		return d.arrayType(t.Elem())
	case *types.Array:
		return d.arrayType(t.Elem())
	case *types.Map:
		// A nil key is never stored, so keys are not nullable.
		return "MapView<" + strings.TrimSuffix(d.tsType(t.Key()), " | null") + ", " + d.tsType(t.Elem()) + ">"
	case *types.Signature:
		return "((" + d.parameters(t, false) + " => " + d.results(t) + ") | null"
	}
	return unknownType
}

func (d *declarer) namedType(t *types.Named) string {
	object := t.Obj()
	if object.Pkg() != nil && object.Pkg().Path() == "iter" {
		arguments := t.TypeArgs()
		switch object.Name() {
		case "Seq":
			return "GoIterable<" + d.tsType(arguments.At(0)) + ">"
		case "Seq2":
			return "GoIterable<[" + d.tsType(arguments.At(0)) + ", " + d.tsType(arguments.At(1)) + "]>"
		}
	}
	if isError(t) {
		return "GoError | null"
	}
	if !d.isExposed(t) {
		if basic, ok := t.Underlying().(*types.Basic); ok {
			return basicType(basic)
		}
		return unknownType
	}
	if types.IsInterface(t) {
		return d.reference(object) + " | null"
	}
	return d.reference(object)
}

// isExposed reports whether a named type is declared by the generator.
func (d *declarer) isExposed(t *types.Named) bool {
	object := t.Obj()
	return object.Pkg() != nil && d.model.declares(object)
}

func (d *declarer) arrayType(element types.Type) string {
	if basic, ok := element.(*types.Basic); ok && basic.Kind() == types.Byte {
		return "string"
	}
	return wrapUnion(d.tsType(element)) + "[]"
}

// signature renders a function or method signature after its name.
func (d *declarer) signature(signature *types.Signature) string {
	return "(" + d.parameters(signature, true) + ": " + d.results(signature)
}

// parameters renders a parameter list including its closing parenthesis.
// When tokens is set, slices of interfaces also accept type tokens, which
// become typed nils. Callbacks receive values from Go, never tokens.
func (d *declarer) parameters(signature *types.Signature, tokens bool) string {
	params := signature.Params()
	rendered := make([]string, 0, params.Len())
	for i := range params.Len() {
		param := params.At(i)
		name := parameterName(param.Name(), i)
		slice, isSlice := types.Unalias(param.Type()).(*types.Slice)
		variadic := signature.Variadic() && i == params.Len()-1
		switch {
		case tokens && isSlice && d.isExposedInterface(slice.Elem()):
			element := d.tsType(slice.Elem()) + " | TypeToken<" + strings.TrimSuffix(d.tsType(slice.Elem()), " | null") + ">"
			rendered = append(rendered, variadicPrefix(variadic)+name+": ("+element+")[]")
		default:
			rendered = append(rendered, variadicPrefix(variadic)+name+": "+d.tsType(param.Type()))
		}
	}
	return strings.Join(rendered, ", ") + ")"
}

func (d *declarer) isExposedInterface(t types.Type) bool {
	named, ok := types.Unalias(t).(*types.Named)
	return ok && types.IsInterface(named) && d.isExposed(named)
}

// results applies the runtime's result conventions: a trailing error throws,
// (T, bool) becomes T | undefined, and other multiple results become tuples.
func (d *declarer) results(signature *types.Signature) string {
	results := slices.Collect(signature.Results().Variables())
	if len(results) > 0 && isError(results[len(results)-1].Type()) {
		results = results[:len(results)-1]
	}
	switch {
	case len(results) == 0:
		return "void"
	case len(results) == 1:
		return d.tsType(results[0].Type())
	case len(results) == 2 && isBool(results[1].Type()) && !isTuple(signature):
		return d.tsType(results[0].Type()) + " | undefined"
	}
	rendered := make([]string, 0, len(results))
	for _, result := range results {
		rendered = append(rendered, d.tsType(result.Type()))
	}
	return "[" + strings.Join(rendered, ", ") + "]"
}
