// Code generated by tsk-gen. DO NOT EDIT.

declare module "go/ast" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as build from "go/build";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as modfile from "golang.org/x/mod/modfile";
  import type * as buildssa from "golang.org/x/tools/go/analysis/passes/buildssa";
  import type * as edge from "golang.org/x/tools/go/ast/edge";
  import type * as inspector from "golang.org/x/tools/go/ast/inspector";
  import type * as ssa from "golang.org/x/tools/go/ssa";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  import type * as fs from "io/fs";
  import type * as os from "os";
  import type * as filepath from "path/filepath";
  export interface ArrayType {
    readonly $type: "ArrayType";
    readonly lbrack: token.Pos;
    readonly len: Expr | null;
    readonly elt: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ArrayType: TypeToken<ArrayType>;
  export interface AssignStmt {
    readonly $type: "AssignStmt";
    readonly lhs: (Expr | null)[];
    readonly tokPos: token.Pos;
    readonly tok: token.Token;
    readonly rhs: (Expr | null)[];
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const AssignStmt: TypeToken<AssignStmt>;
  export const Bad: ObjKind;
  export interface BadDecl {
    readonly $type: "BadDecl";
    readonly from: token.Pos;
    readonly to: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BadDecl: TypeToken<BadDecl>;
  export interface BadExpr {
    readonly $type: "BadExpr";
    readonly from: token.Pos;
    readonly to: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BadExpr: TypeToken<BadExpr>;
  export interface BadStmt {
    readonly $type: "BadStmt";
    readonly from: token.Pos;
    readonly to: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BadStmt: TypeToken<BadStmt>;
  export interface BasicLit {
    readonly $type: "BasicLit";
    readonly valuePos: token.Pos;
    readonly valueEnd: token.Pos;
    readonly kind: token.Token;
    readonly value: string;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BasicLit: TypeToken<BasicLit>;
  export interface BinaryExpr {
    readonly $type: "BinaryExpr";
    readonly x: Expr | null;
    readonly opPos: token.Pos;
    readonly op: token.Token;
    readonly y: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BinaryExpr: TypeToken<BinaryExpr>;
  export interface BlockStmt {
    readonly $type: "BlockStmt";
    readonly lbrace: token.Pos;
    readonly list: (Stmt | null)[];
    readonly rbrace: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BlockStmt: TypeToken<BlockStmt>;
  export interface BranchStmt {
    readonly $type: "BranchStmt";
    readonly tokPos: token.Pos;
    readonly tok: token.Token;
    readonly label: Ident | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const BranchStmt: TypeToken<BranchStmt>;
  export interface CallExpr {
    readonly $type: "CallExpr";
    readonly fun: Expr | null;
    readonly lparen: token.Pos;
    readonly args: (Expr | null)[];
    readonly ellipsis: token.Pos;
    readonly rparen: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const CallExpr: TypeToken<CallExpr>;
  export interface CaseClause {
    readonly $type: "CaseClause";
    readonly case: token.Pos;
    readonly list: (Expr | null)[];
    readonly colon: token.Pos;
    readonly body: (Stmt | null)[];
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const CaseClause: TypeToken<CaseClause>;
  export type ChanDir = number;
  export interface ChanType {
    readonly $type: "ChanType";
    readonly begin: token.Pos;
    readonly arrow: token.Pos;
    readonly dir: ChanDir;
    readonly value: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ChanType: TypeToken<ChanType>;
  export interface CommClause {
    readonly $type: "CommClause";
    readonly case: token.Pos;
    readonly comm: Stmt | null;
    readonly colon: token.Pos;
    readonly body: (Stmt | null)[];
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const CommClause: TypeToken<CommClause>;
  export interface Comment {
    readonly $type: "Comment";
    readonly slash: token.Pos;
    readonly text: string;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const Comment: TypeToken<Comment>;
  export interface CommentGroup {
    readonly $type: "CommentGroup";
    readonly list: (Comment | null)[];
    end(): token.Pos;
    pos(): token.Pos;
    text(): string;
  }
  export const CommentGroup: TypeToken<CommentGroup>;
  export type CommentMap = MapView<Node, (CommentGroup | null)[]>;
  export interface CompositeLit {
    readonly $type: "CompositeLit";
    readonly type: Expr | null;
    readonly lbrace: token.Pos;
    readonly elts: (Expr | null)[];
    readonly rbrace: token.Pos;
    readonly incomplete: boolean;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const CompositeLit: TypeToken<CompositeLit>;
  export const Con: ObjKind;
  export type Decl = BadDecl | FuncDecl | GenDecl;
  export interface DeclStmt {
    readonly $type: "DeclStmt";
    readonly decl: Decl | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const DeclStmt: TypeToken<DeclStmt>;
  export interface DeferStmt {
    readonly $type: "DeferStmt";
    readonly defer: token.Pos;
    readonly call: CallExpr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const DeferStmt: TypeToken<DeferStmt>;
  export interface Directive {
    readonly $type: "Directive";
    readonly tool: string;
    readonly name: string;
    readonly args: string;
    readonly slash: token.Pos;
    readonly argsPos: token.Pos;
    end(): token.Pos;
    parseArgs(): DirectiveArg[];
    pos(): token.Pos;
  }
  export const Directive: TypeToken<Directive>;
  export interface DirectiveArg {
    readonly $type: "DirectiveArg";
    readonly arg: string;
    readonly pos: token.Pos;
  }
  export const DirectiveArg: TypeToken<DirectiveArg>;
  export interface Ellipsis {
    readonly $type: "Ellipsis";
    readonly ellipsis: token.Pos;
    readonly elt: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const Ellipsis: TypeToken<Ellipsis>;
  export interface EmptyStmt {
    readonly $type: "EmptyStmt";
    readonly semicolon: token.Pos;
    readonly implicit: boolean;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const EmptyStmt: TypeToken<EmptyStmt>;
  export type Expr = ArrayType | BadExpr | BasicLit | BinaryExpr | CallExpr | ChanType | CompositeLit | Ellipsis | FuncLit | FuncType | Ident | IndexExpr | IndexListExpr | InterfaceType | KeyValueExpr | MapType | ParenExpr | SelectorExpr | SliceExpr | StarExpr | StructType | TypeAssertExpr | UnaryExpr;
  export interface ExprStmt {
    readonly $type: "ExprStmt";
    readonly x: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ExprStmt: TypeToken<ExprStmt>;
  export interface Field {
    readonly $type: "Field";
    readonly doc: CommentGroup | null;
    readonly names: (Ident | null)[];
    readonly type: Expr | null;
    readonly tag: BasicLit | null;
    readonly comment: CommentGroup | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const Field: TypeToken<Field>;
  export type FieldFilter = ((name: string, value: unknown) => boolean) | null;
  export interface FieldList {
    readonly $type: "FieldList";
    readonly opening: token.Pos;
    readonly list: (Field | null)[];
    readonly closing: token.Pos;
    end(): token.Pos;
    numFields(): number;
    pos(): token.Pos;
  }
  export const FieldList: TypeToken<FieldList>;
  export interface File {
    readonly $type: "File";
    readonly doc: CommentGroup | null;
    readonly package: token.Pos;
    readonly name: Ident | null;
    readonly decls: (Decl | null)[];
    readonly fileStart: token.Pos;
    readonly fileEnd: token.Pos;
    readonly scope: Scope | null;
    readonly imports: (ImportSpec | null)[];
    readonly unresolved: (Ident | null)[];
    readonly comments: (CommentGroup | null)[];
    readonly goVersion: string;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const File: TypeToken<File>;
  export function fileExports(src: File | null): boolean;
  export type Filter = ((arg0: string) => boolean) | null;
  export function filterDecl(decl: Decl | null, f: Filter): boolean;
  export function filterFile(src: File | null, f: Filter): boolean;
  export const FilterFuncDuplicates: MergeMode;
  export const FilterImportDuplicates: MergeMode;
  export function filterPackage(pkg: Package | null, f: Filter): boolean;
  export const FilterUnassociatedComments: MergeMode;
  export interface ForStmt {
    readonly $type: "ForStmt";
    readonly for: token.Pos;
    readonly init: Stmt | null;
    readonly cond: Expr | null;
    readonly post: Stmt | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ForStmt: TypeToken<ForStmt>;
  export function fprint(w: unknown, fset: token.FileSet | null, x: unknown, f: FieldFilter): void;
  export const Fun: ObjKind;
  export interface FuncDecl {
    readonly $type: "FuncDecl";
    readonly doc: CommentGroup | null;
    readonly recv: FieldList | null;
    readonly name: Ident | null;
    readonly type: FuncType | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const FuncDecl: TypeToken<FuncDecl>;
  export interface FuncLit {
    readonly $type: "FuncLit";
    readonly type: FuncType | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const FuncLit: TypeToken<FuncLit>;
  export interface FuncType {
    readonly $type: "FuncType";
    readonly func: token.Pos;
    readonly typeParams: FieldList | null;
    readonly params: FieldList | null;
    readonly results: FieldList | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const FuncType: TypeToken<FuncType>;
  export interface GenDecl {
    readonly $type: "GenDecl";
    readonly doc: CommentGroup | null;
    readonly tokPos: token.Pos;
    readonly tok: token.Token;
    readonly lparen: token.Pos;
    readonly specs: (Spec | null)[];
    readonly rparen: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const GenDecl: TypeToken<GenDecl>;
  export interface GoStmt {
    readonly $type: "GoStmt";
    readonly go: token.Pos;
    readonly call: CallExpr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const GoStmt: TypeToken<GoStmt>;
  export interface Ident {
    readonly $type: "Ident";
    readonly namePos: token.Pos;
    readonly name: string;
    readonly obj: Object | null;
    end(): token.Pos;
    isExported(): boolean;
    pos(): token.Pos;
    string(): string;
  }
  export const Ident: TypeToken<Ident>;
  export interface IfStmt {
    readonly $type: "IfStmt";
    readonly if: token.Pos;
    readonly init: Stmt | null;
    readonly cond: Expr | null;
    readonly body: BlockStmt | null;
    readonly else: Stmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const IfStmt: TypeToken<IfStmt>;
  export interface ImportSpec {
    readonly $type: "ImportSpec";
    readonly doc: CommentGroup | null;
    readonly name: Ident | null;
    readonly path: BasicLit | null;
    readonly comment: CommentGroup | null;
    readonly endPos: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ImportSpec: TypeToken<ImportSpec>;
  export type Importer = ((imports: MapView<string, Object | null>, path: string) => Object | null) | null;
  export interface IncDecStmt {
    readonly $type: "IncDecStmt";
    readonly x: Expr | null;
    readonly tokPos: token.Pos;
    readonly tok: token.Token;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const IncDecStmt: TypeToken<IncDecStmt>;
  export interface IndexExpr {
    readonly $type: "IndexExpr";
    readonly x: Expr | null;
    readonly lbrack: token.Pos;
    readonly index: Expr | null;
    readonly rbrack: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const IndexExpr: TypeToken<IndexExpr>;
  export interface IndexListExpr {
    readonly $type: "IndexListExpr";
    readonly x: Expr | null;
    readonly lbrack: token.Pos;
    readonly indices: (Expr | null)[];
    readonly rbrack: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const IndexListExpr: TypeToken<IndexListExpr>;
  export function inspect(node: Node | null, f: ((arg0: Node | null) => boolean) | null): void;
  export interface InterfaceType {
    readonly $type: "InterfaceType";
    readonly interface: token.Pos;
    readonly methods: FieldList | null;
    readonly incomplete: boolean;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const InterfaceType: TypeToken<InterfaceType>;
  export function isExported(name: string): boolean;
  export function isGenerated(file: File | null): boolean;
  export interface KeyValueExpr {
    readonly $type: "KeyValueExpr";
    readonly key: Expr | null;
    readonly colon: token.Pos;
    readonly value: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const KeyValueExpr: TypeToken<KeyValueExpr>;
  export interface LabeledStmt {
    readonly $type: "LabeledStmt";
    readonly label: Ident | null;
    readonly colon: token.Pos;
    readonly stmt: Stmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const LabeledStmt: TypeToken<LabeledStmt>;
  export const Lbl: ObjKind;
  export interface MapType {
    readonly $type: "MapType";
    readonly map: token.Pos;
    readonly key: Expr | null;
    readonly value: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const MapType: TypeToken<MapType>;
  export type MergeMode = number;
  export function mergePackageFiles(pkg: Package | null, mode: MergeMode): File | null;
  export function newCommentMap(fset: token.FileSet | null, node: Node | null, comments: (CommentGroup | null)[]): CommentMap;
  export function newIdent(name: string): Ident | null;
  export function newObj(kind: ObjKind, name: string): Object | null;
  export function newPackage(fset: token.FileSet | null, files: MapView<string, File | null>, importer: Importer, universe: Scope | null): Package | null;
  export function newScope(outer: Scope | null): Scope | null;
  export type Node = ArrayType | AssignStmt | BadDecl | BadExpr | BadStmt | BasicLit | BinaryExpr | BlockStmt | BranchStmt | CallExpr | CaseClause | ChanType | CommClause | Comment | CommentGroup | CompositeLit | DeclStmt | DeferStmt | Directive | Ellipsis | EmptyStmt | ExprStmt | Field | FieldList | File | ForStmt | FuncDecl | FuncLit | FuncType | GenDecl | GoStmt | Ident | IfStmt | ImportSpec | IncDecStmt | IndexExpr | IndexListExpr | InterfaceType | KeyValueExpr | LabeledStmt | MapType | Package | ParenExpr | RangeStmt | ReturnStmt | SelectStmt | SelectorExpr | SendStmt | SliceExpr | StarExpr | StructType | SwitchStmt | TypeAssertExpr | TypeSpec | TypeSwitchStmt | UnaryExpr | ValueSpec;
  export function notNilFilter(arg0: string, v: unknown): boolean;
  export type ObjKind = number;
  export const ObjKind: {
    string(receiver: ObjKind): string;
  };
  export interface Object {
    readonly $type: "Object";
    readonly kind: ObjKind;
    readonly name: string;
    readonly decl: unknown;
    readonly data: unknown;
    readonly type: unknown;
    pos(): token.Pos;
  }
  export const Object: TypeToken<Object>;
  export interface Package {
    readonly $type: "Package";
    readonly name: string;
    readonly scope: Scope | null;
    readonly imports: MapView<string, Object | null>;
    readonly files: MapView<string, File | null>;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const Package: TypeToken<Package>;
  export function packageExports(pkg: Package | null): boolean;
  export interface ParenExpr {
    readonly $type: "ParenExpr";
    readonly lparen: token.Pos;
    readonly x: Expr | null;
    readonly rparen: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ParenExpr: TypeToken<ParenExpr>;
  export function parseDirective(pos: token.Pos, c: string): Directive | undefined;
  export const Pkg: ObjKind;
  export function preorder(root: Node | null): GoIterable<Node | null>;
  export function preorderStack(root: Node | null, stack: (Node | null | TypeToken<Node>)[], f: ((n: Node | null, stack: (Node | null)[]) => boolean) | null): void;
  export function print(fset: token.FileSet | null, x: unknown): void;
  export const RECV: ChanDir;
  export interface RangeStmt {
    readonly $type: "RangeStmt";
    readonly for: token.Pos;
    readonly key: Expr | null;
    readonly value: Expr | null;
    readonly tokPos: token.Pos;
    readonly tok: token.Token;
    readonly range: token.Pos;
    readonly x: Expr | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const RangeStmt: TypeToken<RangeStmt>;
  export interface ReturnStmt {
    readonly $type: "ReturnStmt";
    readonly return: token.Pos;
    readonly results: (Expr | null)[];
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ReturnStmt: TypeToken<ReturnStmt>;
  export const SEND: ChanDir;
  export interface Scope {
    readonly $type: "Scope";
    readonly outer: Scope | null;
    readonly objects: MapView<string, Object | null>;
    insert(obj: Object | null): Object | null;
    lookup(name: string): Object | null;
    string(): string;
  }
  export const Scope: TypeToken<Scope>;
  export interface SelectStmt {
    readonly $type: "SelectStmt";
    readonly select: token.Pos;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const SelectStmt: TypeToken<SelectStmt>;
  export interface SelectorExpr {
    readonly $type: "SelectorExpr";
    readonly x: Expr | null;
    readonly sel: Ident | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const SelectorExpr: TypeToken<SelectorExpr>;
  export interface SendStmt {
    readonly $type: "SendStmt";
    readonly chan: Expr | null;
    readonly arrow: token.Pos;
    readonly value: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const SendStmt: TypeToken<SendStmt>;
  export interface SliceExpr {
    readonly $type: "SliceExpr";
    readonly x: Expr | null;
    readonly lbrack: token.Pos;
    readonly low: Expr | null;
    readonly high: Expr | null;
    readonly max: Expr | null;
    readonly slice3: boolean;
    readonly rbrack: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const SliceExpr: TypeToken<SliceExpr>;
  export function sortImports(fset: token.FileSet | null, f: File | null): void;
  export type Spec = ImportSpec | TypeSpec | ValueSpec;
  export interface StarExpr {
    readonly $type: "StarExpr";
    readonly star: token.Pos;
    readonly x: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const StarExpr: TypeToken<StarExpr>;
  export type Stmt = AssignStmt | BadStmt | BlockStmt | BranchStmt | CaseClause | CommClause | DeclStmt | DeferStmt | EmptyStmt | ExprStmt | ForStmt | GoStmt | IfStmt | IncDecStmt | LabeledStmt | RangeStmt | ReturnStmt | SelectStmt | SendStmt | SwitchStmt | TypeSwitchStmt;
  export interface StructType {
    readonly $type: "StructType";
    readonly struct: token.Pos;
    readonly fields: FieldList | null;
    readonly incomplete: boolean;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const StructType: TypeToken<StructType>;
  export interface SwitchStmt {
    readonly $type: "SwitchStmt";
    readonly switch: token.Pos;
    readonly init: Stmt | null;
    readonly tag: Expr | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const SwitchStmt: TypeToken<SwitchStmt>;
  export const Typ: ObjKind;
  export interface TypeAssertExpr {
    readonly $type: "TypeAssertExpr";
    readonly x: Expr | null;
    readonly lparen: token.Pos;
    readonly type: Expr | null;
    readonly rparen: token.Pos;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const TypeAssertExpr: TypeToken<TypeAssertExpr>;
  export interface TypeSpec {
    readonly $type: "TypeSpec";
    readonly doc: CommentGroup | null;
    readonly name: Ident | null;
    readonly typeParams: FieldList | null;
    readonly assign: token.Pos;
    readonly type: Expr | null;
    readonly comment: CommentGroup | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const TypeSpec: TypeToken<TypeSpec>;
  export interface TypeSwitchStmt {
    readonly $type: "TypeSwitchStmt";
    readonly switch: token.Pos;
    readonly init: Stmt | null;
    readonly assign: Stmt | null;
    readonly body: BlockStmt | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const TypeSwitchStmt: TypeToken<TypeSwitchStmt>;
  export interface UnaryExpr {
    readonly $type: "UnaryExpr";
    readonly opPos: token.Pos;
    readonly op: token.Token;
    readonly x: Expr | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const UnaryExpr: TypeToken<UnaryExpr>;
  export function unparen(e: Expr | null): Expr | null;
  export interface ValueSpec {
    readonly $type: "ValueSpec";
    readonly doc: CommentGroup | null;
    readonly names: (Ident | null)[];
    readonly type: Expr | null;
    readonly values: (Expr | null)[];
    readonly comment: CommentGroup | null;
    end(): token.Pos;
    pos(): token.Pos;
  }
  export const ValueSpec: TypeToken<ValueSpec>;
  export const Var: ObjKind;
  export interface Visitor {
    readonly $type: string;
    visit(node: Node | null): Visitor | null;
  }
  export function walk(v: Visitor | null, node: Node | null): void;
}
