// Code generated by tsk-gen. DO NOT EDIT.

declare module "go/build" {
  import type { GoError, MapView, TypeToken } from "tsk";
  import type * as token from "go/token";
  import type * as fs from "io/fs";
  export const AllowBinary: ImportMode;
  export function archChar(goarch: string): string;
  export interface Context {
    readonly $type: "Context";
    readonly goarch: string;
    readonly goos: string;
    readonly goroot: string;
    readonly gopath: string;
    readonly dir: string;
    readonly cgoEnabled: boolean;
    readonly useAllFiles: boolean;
    readonly compiler: string;
    readonly buildTags: string[];
    readonly toolTags: string[];
    readonly releaseTags: string[];
    readonly installSuffix: string;
    readonly joinPath: ((...elem: string[]) => string) | null;
    readonly splitPathList: ((list: string) => string[]) | null;
    readonly isAbsPath: ((path: string) => boolean) | null;
    readonly isDir: ((path: string) => boolean) | null;
    readonly hasSubdir: ((root: string, dir: string) => string | undefined) | null;
    readonly readDir: ((dir: string) => (fs.FileInfo | null)[]) | null;
    readonly openFile: ((path: string) => unknown) | null;
    import(path: string, srcDir: string, mode: ImportMode): Package | null;
    importDir(dir: string, mode: ImportMode): Package | null;
    matchFile(dir: string, name: string): boolean;
    srcDirs(): string[];
  }
  export const Context: TypeToken<Context>;
  export const Default: Context;
  export interface Directive {
    readonly $type: "Directive";
    readonly text: string;
    readonly pos: token.Position;
  }
  export const Directive: TypeToken<Directive>;
  export const FindOnly: ImportMode;
  export const IgnoreVendor: ImportMode;
  export function import_(path: string, srcDir: string, mode: ImportMode): Package | null;
  export const ImportComment: ImportMode;
  export function importDir(dir: string, mode: ImportMode): Package | null;
  export type ImportMode = number;
  export function isLocalImport(path: string): boolean;
  export class MultiplePackageError extends GoError {
    private constructor();
    readonly $type: "MultiplePackageError";
    readonly dir: string;
    readonly packages: string[];
    readonly files: string[];
    error(): string;
  }
  export class NoGoError extends GoError {
    private constructor();
    readonly $type: "NoGoError";
    readonly dir: string;
    error(): string;
  }
  export interface Package {
    readonly $type: "Package";
    readonly dir: string;
    readonly name: string;
    readonly importComment: string;
    readonly doc: string;
    readonly importPath: string;
    readonly root: string;
    readonly srcRoot: string;
    readonly pkgRoot: string;
    readonly pkgTargetRoot: string;
    readonly binDir: string;
    readonly goroot: boolean;
    readonly pkgObj: string;
    readonly allTags: string[];
    readonly conflictDir: string;
    readonly binaryOnly: boolean;
    readonly goFiles: string[];
    readonly cgoFiles: string[];
    readonly ignoredGoFiles: string[];
    readonly invalidGoFiles: string[];
    readonly ignoredOtherFiles: string[];
    readonly cFiles: string[];
    readonly cxxFiles: string[];
    readonly mFiles: string[];
    readonly hFiles: string[];
    readonly fFiles: string[];
    readonly sFiles: string[];
    readonly swigFiles: string[];
    readonly swigCXXFiles: string[];
    readonly sysoFiles: string[];
    readonly cgoCFLAGS: string[];
    readonly cgoCPPFLAGS: string[];
    readonly cgoCXXFLAGS: string[];
    readonly cgoFFLAGS: string[];
    readonly cgoLDFLAGS: string[];
    readonly cgoPkgConfig: string[];
    readonly testGoFiles: string[];
    readonly xTestGoFiles: string[];
    readonly directives: Directive[];
    readonly testDirectives: Directive[];
    readonly xTestDirectives: Directive[];
    readonly imports: string[];
    readonly importPos: MapView<string, token.Position[]>;
    readonly testImports: string[];
    readonly testImportPos: MapView<string, token.Position[]>;
    readonly xTestImports: string[];
    readonly xTestImportPos: MapView<string, token.Position[]>;
    readonly embedPatterns: string[];
    readonly embedPatternPos: MapView<string, token.Position[]>;
    readonly testEmbedPatterns: string[];
    readonly testEmbedPatternPos: MapView<string, token.Position[]>;
    readonly xTestEmbedPatterns: string[];
    readonly xTestEmbedPatternPos: MapView<string, token.Position[]>;
    isCommand(): boolean;
  }
  export const Package: TypeToken<Package>;
  export const ToolDir: string;
}
