// Code generated by tsk-gen. DO NOT EDIT.

declare module "go/constant" {
  import type * as token from "go/token";
  export function binaryOp(x_: Value | null, op: token.Token, y_: Value | null): Value | null;
  export function bitLen(x: Value | null): number;
  export const Bool: Kind;
  export function boolVal(x: Value | null): boolean;
  export function bytes(x: Value | null): string;
  export function compare(x_: Value | null, op: token.Token, y_: Value | null): boolean;
  export const Complex: Kind;
  export function denom(x: Value | null): Value | null;
  export const Float: Kind;
  export function float32Val(x: Value | null): number | undefined;
  export function float64Val(x: Value | null): number | undefined;
  export function imag(x: Value | null): Value | null;
  export const Int: Kind;
  export function int64Val(x: Value | null): number | undefined;
  export type Kind = number;
  export const Kind: {
    string(receiver: Kind): string;
  };
  export function make(x: unknown): Value | null;
  export function makeBool(b: boolean): Value | null;
  export function makeFloat64(x: number): Value | null;
  export function makeFromBytes(bytes: string): Value | null;
  export function makeFromLiteral(lit: string, tok: token.Token, zero: number): Value | null;
  export function makeImag(x: Value | null): Value | null;
  export function makeInt64(x: number): Value | null;
  export function makeString(s: string): Value | null;
  export function makeUint64(x: number): Value | null;
  export function makeUnknown(): Value | null;
  export function num(x: Value | null): Value | null;
  export function real(x: Value | null): Value | null;
  export function shift(x: Value | null, op: token.Token, s: number): Value | null;
  export function sign(x: Value | null): number;
  export const String: Kind;
  export function stringLen(x: Value | null): number;
  export function stringVal(x: Value | null): string;
  export function toComplex(x: Value | null): Value | null;
  export function toFloat(x: Value | null): Value | null;
  export function toInt(x: Value | null): Value | null;
  export function uint64Val(x: Value | null): number | undefined;
  export function unaryOp(op: token.Token, y: Value | null, prec: number): Value | null;
  export const Unknown: Kind;
  export function val(x: Value | null): unknown;
  export interface Value {
    readonly $type: string;
    exactString(): string;
    kind(): Kind;
    string(): string;
  }
}
