// Code generated by tsk-gen. DO NOT EDIT.

declare module "go/parser" {
  import type { MapView } from "tsk";
  import type * as ast from "go/ast";
  import type * as token from "go/token";
  import type * as fs from "io/fs";
  export const AllErrors: Mode;
  export const DeclarationErrors: Mode;
  export const ImportsOnly: Mode;
  export type Mode = number;
  export const PackageClauseOnly: Mode;
  export const ParseComments: Mode;
  export function parseDir(fset: token.FileSet | null, path: string, filter: ((arg0: fs.FileInfo | null) => boolean) | null, mode: Mode): MapView<string, ast.Package | null>;
  export function parseExpr(x: string): ast.Expr | null;
  export function parseExprFrom(fset: token.FileSet | null, filename: string, src: unknown, mode: Mode): ast.Expr | null;
  export function parseFile(fset: token.FileSet | null, filename: string, src: unknown, mode: Mode): ast.File | null;
  export const SkipObjectResolution: Mode;
  export const SpuriousErrors: Mode;
  export const Trace: Mode;
}
