// Code generated by tsk-gen. DO NOT EDIT.

declare module "go/types" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  export interface Alias {
    readonly $type: "Alias";
    obj(): TypeName | null;
    origin(): Alias | null;
    rhs(): Type | null;
    setTypeParams(tparams: (TypeParam | null)[]): void;
    string(): string;
    typeArgs(): TypeList | null;
    typeParams(): TypeParamList | null;
    underlying(): Type | null;
  }
  export const Alias: TypeToken<Alias>;
  export class ArgumentError extends GoError {
    private constructor();
    readonly $type: "ArgumentError";
    readonly index: number;
    readonly err: GoError | null;
    error(): string;
    unwrap(): void;
  }
  export interface Array {
    readonly $type: "Array";
    elem(): Type | null;
    len(): number;
    string(): string;
    underlying(): Type | null;
  }
  export const Array: TypeToken<Array>;
  export function assertableTo(V: Interface | null, T: Type | null): boolean;
  export function assignableTo(V: Type | null, T: Type | null): boolean;
  export interface Basic {
    readonly $type: "Basic";
    info(): BasicInfo;
    kind(): BasicKind;
    name(): string;
    string(): string;
    underlying(): Type | null;
  }
  export const Basic: TypeToken<Basic>;
  export type BasicInfo = number;
  export type BasicKind = number;
  export const Bool: BasicKind;
  export interface Builtin {
    readonly $type: "Builtin";
    exported(): boolean;
    id(): string;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
  }
  export const Builtin: TypeToken<Builtin>;
  export const Byte: BasicKind;
  export interface Chan {
    readonly $type: "Chan";
    dir(): ChanDir;
    elem(): Type | null;
    string(): string;
    underlying(): Type | null;
  }
  export const Chan: TypeToken<Chan>;
  export type ChanDir = number;
  export function checkExpr(fset: token.FileSet | null, pkg: Package | null, pos: token.Pos, expr: ast.Expr | null, info: Info | null): void;
  export interface Checker {
    readonly $type: "Checker";
    readonly info: Info | null;
    readonly types: MapView<ast.Expr, TypeAndValue>;
    readonly instances: MapView<ast.Ident, Instance>;
    readonly defs: MapView<ast.Ident, Object | null>;
    readonly uses: MapView<ast.Ident, Object | null>;
    readonly implicits: MapView<ast.Node, Object | null>;
    readonly selections: MapView<ast.SelectorExpr, Selection | null>;
    readonly scopes: MapView<ast.Node, Scope | null>;
    readonly initOrder: (Initializer | null)[];
    readonly fileVersions: MapView<ast.File, string>;
    files(files: (ast.File | null)[]): void;
    objectOf(id: ast.Ident | null): Object | null;
    pkgNameOf(imp: ast.ImportSpec | null): PkgName | null;
    typeOf(e: ast.Expr | null): Type | null;
  }
  export const Checker: TypeToken<Checker>;
  export function comparable(T: Type | null): boolean;
  export const Complex128: BasicKind;
  export const Complex64: BasicKind;
  export interface Config {
    readonly $type: "Config";
    readonly context: Context | null;
    readonly goVersion: string;
    readonly ignoreFuncBodies: boolean;
    readonly fakeImportC: boolean;
    readonly error: ((err: GoError | null) => void) | null;
    readonly importer: Importer | null;
    readonly sizes: Sizes | null;
    readonly disableUnusedImportCheck: boolean;
    check(path: string, fset: token.FileSet | null, files: (ast.File | null)[], info: Info | null): Package | null;
  }
  export const Config: TypeToken<Config>;
  export interface Const {
    readonly $type: "Const";
    exported(): boolean;
    id(): string;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
    val(): constant.Value | null;
  }
  export const Const: TypeToken<Const>;
  export interface Context {
    readonly $type: "Context";
  }
  export const Context: TypeToken<Context>;
  export function convertibleTo(V: Type | null, T: Type | null): boolean;
  export function defPredeclaredTestFuncs(): void;
  export function default_(t: Type | null): Type | null;
  export class Error extends GoError {
    private constructor();
    readonly $type: "Error";
    readonly fset: token.FileSet | null;
    readonly pos: token.Pos;
    readonly msg: string;
    readonly soft: boolean;
    error(): string;
  }
  export function eval_(fset: token.FileSet | null, pkg: Package | null, pos: token.Pos, expr: string): TypeAndValue;
  export function exprString(x: ast.Expr | null): string;
  export const FieldVal: SelectionKind;
  export const FieldVar: VarKind;
  export const Float32: BasicKind;
  export const Float64: BasicKind;
  export interface Func {
    readonly $type: "Func";
    exported(): boolean;
    fullName(): string;
    id(): string;
    name(): string;
    origin(): Func | null;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    scope(): Scope | null;
    signature(): Signature | null;
    string(): string;
    type(): Type | null;
  }
  export const Func: TypeToken<Func>;
  export interface Hasher {
    readonly $type: "Hasher";
    equal(x: Type | null, y: Type | null): boolean;
    hash(h: unknown, t: Type | null): void;
  }
  export const Hasher: TypeToken<Hasher>;
  export interface HasherIgnoreTags {
    readonly $type: "HasherIgnoreTags";
    equal(x: Type | null, y: Type | null): boolean;
    hash(h: unknown, t: Type | null): void;
  }
  export const HasherIgnoreTags: TypeToken<HasherIgnoreTags>;
  export function id(pkg: Package | null, name: string): string;
  export function identical(x: Type | null, y: Type | null): boolean;
  export function identicalIgnoreTags(x: Type | null, y: Type | null): boolean;
  export function implements_(V: Type | null, T: Interface | null): boolean;
  export type ImportMode = number;
  export interface Importer {
    readonly $type: string;
    import(path: string): Package | null;
  }
  export interface ImporterFrom {
    readonly $type: string;
    import(path: string): Package | null;
    importFrom(path: string, dir: string, mode: ImportMode): Package | null;
  }
  export interface Info {
    readonly $type: "Info";
    readonly types: MapView<ast.Expr, TypeAndValue>;
    readonly instances: MapView<ast.Ident, Instance>;
    readonly defs: MapView<ast.Ident, Object | null>;
    readonly uses: MapView<ast.Ident, Object | null>;
    readonly implicits: MapView<ast.Node, Object | null>;
    readonly selections: MapView<ast.SelectorExpr, Selection | null>;
    readonly scopes: MapView<ast.Node, Scope | null>;
    readonly initOrder: (Initializer | null)[];
    readonly fileVersions: MapView<ast.File, string>;
    objectOf(id: ast.Ident | null): Object | null;
    pkgNameOf(imp: ast.ImportSpec | null): PkgName | null;
    typeOf(e: ast.Expr | null): Type | null;
  }
  export const Info: TypeToken<Info>;
  export interface Initializer {
    readonly $type: "Initializer";
    readonly lhs: (Var | null)[];
    readonly rhs: ast.Expr | null;
    string(): string;
  }
  export const Initializer: TypeToken<Initializer>;
  export interface Instance {
    readonly $type: "Instance";
    readonly typeArgs: TypeList | null;
    readonly type: Type | null;
    string(): string;
  }
  export const Instance: TypeToken<Instance>;
  export function instantiate(ctxt: Context | null, orig: Type | null, targs: (Type | null | TypeToken<Type>)[], validate: boolean): Type | null;
  export const Int: BasicKind;
  export const Int16: BasicKind;
  export const Int32: BasicKind;
  export const Int64: BasicKind;
  export const Int8: BasicKind;
  export interface Interface {
    readonly $type: "Interface";
    complete(): Interface | null;
    embedded(i: number): Named | null;
    embeddedType(i: number): Type | null;
    embeddedTypes(): GoIterable<Type | null>;
    empty(): boolean;
    explicitMethod(i: number): Func | null;
    explicitMethods(): GoIterable<Func | null>;
    isComparable(): boolean;
    isImplicit(): boolean;
    isMethodSet(): boolean;
    markImplicit(): void;
    method(i: number): Func | null;
    methods(): GoIterable<Func | null>;
    numEmbeddeds(): number;
    numExplicitMethods(): number;
    numMethods(): number;
    string(): string;
    underlying(): Type | null;
  }
  export const Interface: TypeToken<Interface>;
  export const Invalid: BasicKind;
  export const IsBoolean: BasicInfo;
  export const IsComplex: BasicInfo;
  export const IsConstType: BasicInfo;
  export const IsFloat: BasicInfo;
  export const IsInteger: BasicInfo;
  export function isInterface(t: Type | null): boolean;
  export const IsNumeric: BasicInfo;
  export const IsOrdered: BasicInfo;
  export const IsString: BasicInfo;
  export const IsUnsigned: BasicInfo;
  export const IsUntyped: BasicInfo;
  export interface Label {
    readonly $type: "Label";
    exported(): boolean;
    id(): string;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
  }
  export const Label: TypeToken<Label>;
  export const LocalVar: VarKind;
  export function lookupFieldOrMethod(T: Type | null, addressable: boolean, pkg: Package | null, name: string): [Object | null, number[], boolean];
  export function lookupSelection(T: Type | null, addressable: boolean, pkg: Package | null, name: string): Selection | undefined;
  export interface Map {
    readonly $type: "Map";
    elem(): Type | null;
    key(): Type | null;
    string(): string;
    underlying(): Type | null;
  }
  export const Map: TypeToken<Map>;
  export const MethodExpr: SelectionKind;
  export interface MethodSet {
    readonly $type: "MethodSet";
    at(i: number): Selection | null;
    len(): number;
    lookup(pkg: Package | null, name: string): Selection | null;
    methods(): GoIterable<Selection | null>;
    string(): string;
  }
  export const MethodSet: TypeToken<MethodSet>;
  export const MethodVal: SelectionKind;
  export function missingMethod(V: Type | null, T: Interface | null, static_: boolean): [Func | null, boolean];
  export interface Named {
    readonly $type: "Named";
    addMethod(m: Func | null): void;
    method(i: number): Func | null;
    methods(): GoIterable<Func | null>;
    numMethods(): number;
    obj(): TypeName | null;
    origin(): Named | null;
    setTypeParams(tparams: (TypeParam | null)[]): void;
    setUnderlying(u: Type | null): void;
    string(): string;
    typeArgs(): TypeList | null;
    typeParams(): TypeParamList | null;
    underlying(): Type | null;
  }
  export const Named: TypeToken<Named>;
  export function newAlias(obj: TypeName | null, rhs: Type | null): Alias | null;
  export function newArray(elem: Type | null, len: number): Array | null;
  export function newChan(dir: ChanDir, elem: Type | null): Chan | null;
  export function newChecker(conf: Config | null, fset: token.FileSet | null, pkg: Package | null, info: Info | null): Checker | null;
  export function newConst(pos: token.Pos, pkg: Package | null, name: string, typ: Type | null, val: constant.Value | null): Const | null;
  export function newContext(): Context | null;
  export function newField(pos: token.Pos, pkg: Package | null, name: string, typ: Type | null, embedded: boolean): Var | null;
  export function newFunc(pos: token.Pos, pkg: Package | null, name: string, sig: Signature | null): Func | null;
  export function newInterface(methods: (Func | null)[], embeddeds: (Named | null)[]): Interface | null;
  export function newInterfaceType(methods: (Func | null)[], embeddeds: (Type | null | TypeToken<Type>)[]): Interface | null;
  export function newLabel(pos: token.Pos, pkg: Package | null, name: string): Label | null;
  export function newMap(key: Type | null, elem: Type | null): Map | null;
  export function newMethodSet(T: Type | null): MethodSet | null;
  export function newNamed(obj: TypeName | null, underlying: Type | null, methods: (Func | null)[]): Named | null;
  export function newPackage(path: string, name: string): Package | null;
  export function newParam(pos: token.Pos, pkg: Package | null, name: string, typ: Type | null): Var | null;
  export function newPkgName(pos: token.Pos, pkg: Package | null, name: string, imported: Package | null): PkgName | null;
  export function newPointer(elem: Type | null): Pointer | null;
  export function newScope(parent: Scope | null, pos: token.Pos, end: token.Pos, comment: string): Scope | null;
  export function newSignature(recv: Var | null, params: Tuple | null, results: Tuple | null, variadic: boolean): Signature | null;
  export function newSignatureType(recv: Var | null, recvTypeParams: (TypeParam | null)[], typeParams: (TypeParam | null)[], params: Tuple | null, results: Tuple | null, variadic: boolean): Signature | null;
  export function newSlice(elem: Type | null): Slice | null;
  export function newStruct(fields: (Var | null)[], tags: string[]): Struct | null;
  export function newTerm(tilde: boolean, typ: Type | null): Term | null;
  export function newTuple(...x: (Var | null)[]): Tuple | null;
  export function newTypeName(pos: token.Pos, pkg: Package | null, name: string, typ: Type | null): TypeName | null;
  export function newTypeParam(obj: TypeName | null, constraint: Type | null): TypeParam | null;
  export function newUnion(terms: (Term | null)[]): Union | null;
  export function newVar(pos: token.Pos, pkg: Package | null, name: string, typ: Type | null): Var | null;
  export interface Nil {
    readonly $type: "Nil";
    exported(): boolean;
    id(): string;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
  }
  export const Nil: TypeToken<Nil>;
  export type Object = Builtin | Const | Func | Label | Nil | PkgName | TypeName | Var;
  export function objectString(obj: Object | null, qf: Qualifier): string;
  export interface Package {
    readonly $type: "Package";
    complete(): boolean;
    goVersion(): string;
    imports(): (Package | null)[];
    markComplete(): void;
    name(): string;
    path(): string;
    scope(): Scope | null;
    setImports(list: (Package | null)[]): void;
    setName(name: string): void;
    string(): string;
  }
  export const Package: TypeToken<Package>;
  export const PackageVar: VarKind;
  export const ParamVar: VarKind;
  export interface PkgName {
    readonly $type: "PkgName";
    exported(): boolean;
    id(): string;
    imported(): Package | null;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
  }
  export const PkgName: TypeToken<PkgName>;
  export interface Pointer {
    readonly $type: "Pointer";
    elem(): Type | null;
    string(): string;
    underlying(): Type | null;
  }
  export const Pointer: TypeToken<Pointer>;
  export type Qualifier = ((arg0: Package | null) => string) | null;
  export const RecvOnly: ChanDir;
  export const RecvVar: VarKind;
  export function relativeTo(pkg: Package | null): Qualifier;
  export const ResultVar: VarKind;
  export const Rune: BasicKind;
  export function satisfies(V: Type | null, T: Interface | null): boolean;
  export interface Scope {
    readonly $type: "Scope";
    child(i: number): Scope | null;
    children(): GoIterable<Scope | null>;
    contains(pos: token.Pos): boolean;
    end(): token.Pos;
    innermost(pos: token.Pos): Scope | null;
    insert(obj: Object | null): Object | null;
    len(): number;
    lookup(name: string): Object | null;
    lookupParent(name: string, pos: token.Pos): [Scope | null, Object | null];
    names(): string[];
    numChildren(): number;
    parent(): Scope | null;
    pos(): token.Pos;
    string(): string;
    writeTo(w: unknown, n: number, recurse: boolean): void;
  }
  export const Scope: TypeToken<Scope>;
  export interface Selection {
    readonly $type: "Selection";
    index(): number[];
    indirect(): boolean;
    kind(): SelectionKind;
    obj(): Object | null;
    recv(): Type | null;
    string(): string;
    type(): Type | null;
  }
  export const Selection: TypeToken<Selection>;
  export type SelectionKind = number;
  export function selectionString(s: Selection | null, qf: Qualifier): string;
  export const SendOnly: ChanDir;
  export const SendRecv: ChanDir;
  export interface Signature {
    readonly $type: "Signature";
    params(): Tuple | null;
    recv(): Var | null;
    recvTypeParams(): TypeParamList | null;
    results(): Tuple | null;
    string(): string;
    typeParams(): TypeParamList | null;
    underlying(): Type | null;
    variadic(): boolean;
  }
  export const Signature: TypeToken<Signature>;
  export interface Sizes {
    readonly $type: string;
    alignof(T: Type | null): number;
    offsetsof(fields: (Var | null)[]): number[];
    sizeof(T: Type | null): number;
  }
  export function sizesFor(compiler: string, arch: string): Sizes | null;
  export interface Slice {
    readonly $type: "Slice";
    elem(): Type | null;
    string(): string;
    underlying(): Type | null;
  }
  export const Slice: TypeToken<Slice>;
  export interface StdSizes {
    readonly $type: "StdSizes";
    readonly wordSize: number;
    readonly maxAlign: number;
    alignof(T: Type | null): number;
    offsetsof(fields: (Var | null)[]): number[];
    sizeof(T: Type | null): number;
  }
  export const StdSizes: TypeToken<StdSizes>;
  export const String: BasicKind;
  export interface Struct {
    readonly $type: "Struct";
    field(i: number): Var | null;
    fields(): GoIterable<Var | null>;
    numFields(): number;
    string(): string;
    tag(i: number): string;
    underlying(): Type | null;
  }
  export const Struct: TypeToken<Struct>;
  export interface Term {
    readonly $type: "Term";
    string(): string;
    tilde(): boolean;
    type(): Type | null;
  }
  export const Term: TypeToken<Term>;
  export interface Tuple {
    readonly $type: "Tuple";
    at(i: number): Var | null;
    len(): number;
    string(): string;
    underlying(): Type | null;
    variables(): GoIterable<Var | null>;
  }
  export const Tuple: TypeToken<Tuple>;
  export const Typ: (Basic | null)[];
  export type Type = Alias | Array | Basic | Chan | Interface | Map | Named | Pointer | Signature | Slice | Struct | Tuple | TypeParam | Union;
  export interface TypeAndValue {
    readonly $type: "TypeAndValue";
    readonly type: Type | null;
    readonly value: constant.Value | null;
    addressable(): boolean;
    assignable(): boolean;
    hasOk(): boolean;
    isBuiltin(): boolean;
    isNil(): boolean;
    isType(): boolean;
    isValue(): boolean;
    isVoid(): boolean;
  }
  export const TypeAndValue: TypeToken<TypeAndValue>;
  export interface TypeList {
    readonly $type: "TypeList";
    at(i: number): Type | null;
    len(): number;
    string(): string;
    types(): GoIterable<Type | null>;
  }
  export const TypeList: TypeToken<TypeList>;
  export interface TypeName {
    readonly $type: "TypeName";
    exported(): boolean;
    id(): string;
    isAlias(): boolean;
    name(): string;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    string(): string;
    type(): Type | null;
  }
  export const TypeName: TypeToken<TypeName>;
  export interface TypeParam {
    readonly $type: "TypeParam";
    constraint(): Type | null;
    index(): number;
    obj(): TypeName | null;
    setConstraint(bound: Type | null): void;
    string(): string;
    underlying(): Type | null;
  }
  export const TypeParam: TypeToken<TypeParam>;
  export interface TypeParamList {
    readonly $type: "TypeParamList";
    at(i: number): TypeParam | null;
    len(): number;
    string(): string;
    typeParams(): GoIterable<TypeParam | null>;
  }
  export const TypeParamList: TypeToken<TypeParamList>;
  export function typeString(typ: Type | null, qf: Qualifier): string;
  export const Uint: BasicKind;
  export const Uint16: BasicKind;
  export const Uint32: BasicKind;
  export const Uint64: BasicKind;
  export const Uint8: BasicKind;
  export const Uintptr: BasicKind;
  export function unalias(t: Type | null): Type | null;
  export interface Union {
    readonly $type: "Union";
    len(): number;
    string(): string;
    term(i: number): Term | null;
    terms(): GoIterable<Term | null>;
    underlying(): Type | null;
  }
  export const Union: TypeToken<Union>;
  export const Universe: Scope | null;
  export const Unsafe: Package | null;
  export const UnsafePointer: BasicKind;
  export const UntypedBool: BasicKind;
  export const UntypedComplex: BasicKind;
  export const UntypedFloat: BasicKind;
  export const UntypedInt: BasicKind;
  export const UntypedNil: BasicKind;
  export const UntypedRune: BasicKind;
  export const UntypedString: BasicKind;
  export interface Var {
    readonly $type: "Var";
    anonymous(): boolean;
    embedded(): boolean;
    exported(): boolean;
    id(): string;
    isField(): boolean;
    kind(): VarKind;
    name(): string;
    origin(): Var | null;
    parent(): Scope | null;
    pkg(): Package | null;
    pos(): token.Pos;
    setKind(kind: VarKind): void;
    string(): string;
    type(): Type | null;
  }
  export const Var: TypeToken<Var>;
  export type VarKind = number;
  export const VarKind: {
    string(receiver: VarKind): string;
  };
  export function writeExpr(buf: unknown, x: ast.Expr | null): void;
  export function writeSignature(buf: unknown, sig: Signature | null, qf: Qualifier): void;
  export function writeType(buf: unknown, typ: Type | null, qf: Qualifier): void;
}
