// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/ssa" {
  import type { MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  export interface Alloc {
    readonly $type: "Alloc";
    readonly comment: string;
    readonly heap: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Alloc: TypeToken<Alloc>;
  export const BareInits: BuilderMode;
  export interface BasicBlock {
    readonly $type: "BasicBlock";
    readonly index: number;
    readonly comment: string;
    readonly instrs: (Instruction | null)[];
    readonly preds: (BasicBlock | null)[];
    readonly succs: (BasicBlock | null)[];
    dominates(c: BasicBlock | null): boolean;
    dominees(): (BasicBlock | null)[];
    idom(): BasicBlock | null;
    parent(): Function | null;
    string(): string;
  }
  export const BasicBlock: TypeToken<BasicBlock>;
  export interface BinOp {
    readonly $type: "BinOp";
    readonly op: token.Token;
    readonly x: Value | null;
    readonly y: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const BinOp: TypeToken<BinOp>;
  export const BuildSerially: BuilderMode;
  export type BuilderMode = number;
  export const BuilderMode: {
    get(receiver: BuilderMode): unknown;
    string(receiver: BuilderMode): string;
  };
  export const BuilderModeDoc: string;
  export interface Builtin {
    readonly $type: "Builtin";
    name(): string;
    object(): types.Object | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Builtin: TypeToken<Builtin>;
  export interface Call {
    readonly $type: "Call";
    readonly call: CallCommon;
    block(): BasicBlock | null;
    common(): CallCommon | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
    value(): Call | null;
  }
  export const Call: TypeToken<Call>;
  export interface CallCommon {
    readonly $type: "CallCommon";
    readonly value: Value | null;
    readonly method: types.Func | null;
    readonly args: (Value | null)[];
    description(): string;
    isInvoke(): boolean;
    operands(rands: (Value | null)[]): (Value | null)[];
    pos(): token.Pos;
    signature(): types.Signature | null;
    staticCallee(): Function | null;
    string(): string;
  }
  export const CallCommon: TypeToken<CallCommon>;
  export type CallInstruction = Call | Defer | Go;
  export interface ChangeInterface {
    readonly $type: "ChangeInterface";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const ChangeInterface: TypeToken<ChangeInterface>;
  export interface ChangeType {
    readonly $type: "ChangeType";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const ChangeType: TypeToken<ChangeType>;
  export interface Const {
    readonly $type: "Const";
    readonly value: constant.Value | null;
    complex128(): unknown;
    float64(): number;
    int64(): number;
    isNil(): boolean;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    relString(from: types.Package | null): string;
    string(): string;
    type(): types.Type | null;
    uint64(): number;
  }
  export const Const: TypeToken<Const>;
  export interface Convert {
    readonly $type: "Convert";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Convert: TypeToken<Convert>;
  export interface DebugRef {
    readonly $type: "DebugRef";
    readonly expr: ast.Expr | null;
    readonly isAddr: boolean;
    readonly x: Value | null;
    block(): BasicBlock | null;
    object(): types.Object | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const DebugRef: TypeToken<DebugRef>;
  export interface Defer {
    readonly $type: "Defer";
    readonly call: CallCommon;
    readonly deferStack: Value | null;
    block(): BasicBlock | null;
    common(): CallCommon | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    value(): Call | null;
  }
  export const Defer: TypeToken<Defer>;
  export function enclosingFunction(pkg: Package | null, path: (ast.Node | null | TypeToken<ast.Node>)[]): Function | null;
  export interface Extract {
    readonly $type: "Extract";
    readonly tuple: Value | null;
    readonly index: number;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Extract: TypeToken<Extract>;
  export interface Field {
    readonly $type: "Field";
    readonly x: Value | null;
    readonly field: number;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Field: TypeToken<Field>;
  export interface FieldAddr {
    readonly $type: "FieldAddr";
    readonly x: Value | null;
    readonly field: number;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const FieldAddr: TypeToken<FieldAddr>;
  export interface FreeVar {
    readonly $type: "FreeVar";
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const FreeVar: TypeToken<FreeVar>;
  export interface Function {
    readonly $type: "Function";
    readonly signature: types.Signature | null;
    readonly synthetic: string;
    readonly pkg: Package | null;
    readonly prog: Program | null;
    readonly params: (Parameter | null)[];
    readonly freeVars: (FreeVar | null)[];
    readonly locals: (Alloc | null)[];
    readonly blocks: (BasicBlock | null)[];
    readonly recover: BasicBlock | null;
    readonly anonFuncs: (Function | null)[];
    domPostorder(): (BasicBlock | null)[];
    domPreorder(): (BasicBlock | null)[];
    name(): string;
    object(): types.Object | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    origin(): Function | null;
    package(): Package | null;
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    relString(from: types.Package | null): string;
    string(): string;
    syntax(): ast.Node | null;
    token(): token.Token;
    type(): types.Type | null;
    typeArgs(): (types.Type | null)[];
    typeParams(): types.TypeParamList | null;
    valueForExpr(e: ast.Expr | null): [Value | null, boolean];
    writeTo(w: unknown): number;
  }
  export const Function: TypeToken<Function>;
  export interface Global {
    readonly $type: "Global";
    readonly pkg: Package | null;
    name(): string;
    object(): types.Object | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    package(): Package | null;
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    relString(from: types.Package | null): string;
    string(): string;
    token(): token.Token;
    type(): types.Type | null;
  }
  export const Global: TypeToken<Global>;
  export const GlobalDebug: BuilderMode;
  export interface Go {
    readonly $type: "Go";
    readonly call: CallCommon;
    block(): BasicBlock | null;
    common(): CallCommon | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    value(): Call | null;
  }
  export const Go: TypeToken<Go>;
  export function hasEnclosingFunction(pkg: Package | null, path: (ast.Node | null | TypeToken<ast.Node>)[]): boolean;
  export interface If {
    readonly $type: "If";
    readonly cond: Value | null;
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const If: TypeToken<If>;
  export interface Index {
    readonly $type: "Index";
    readonly x: Value | null;
    readonly index: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Index: TypeToken<Index>;
  export interface IndexAddr {
    readonly $type: "IndexAddr";
    readonly x: Value | null;
    readonly index: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const IndexAddr: TypeToken<IndexAddr>;
  export const InstantiateGenerics: BuilderMode;
  export type Instruction = Alloc | BinOp | Call | ChangeInterface | ChangeType | Convert | DebugRef | Defer | Extract | Field | FieldAddr | Go | If | Index | IndexAddr | Jump | Lookup | MakeChan | MakeClosure | MakeInterface | MakeMap | MakeSlice | MapUpdate | MultiConvert | Next | Panic | Phi | Range | Return | RunDefers | Select | Send | Slice | SliceToArrayPointer | Store | TypeAssert | UnOp;
  export interface Jump {
    readonly $type: "Jump";
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const Jump: TypeToken<Jump>;
  export const LogSource: BuilderMode;
  export interface Lookup {
    readonly $type: "Lookup";
    readonly x: Value | null;
    readonly index: Value | null;
    readonly commaOk: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Lookup: TypeToken<Lookup>;
  export interface MakeChan {
    readonly $type: "MakeChan";
    readonly size: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MakeChan: TypeToken<MakeChan>;
  export interface MakeClosure {
    readonly $type: "MakeClosure";
    readonly fn: Value | null;
    readonly bindings: (Value | null)[];
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MakeClosure: TypeToken<MakeClosure>;
  export interface MakeInterface {
    readonly $type: "MakeInterface";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MakeInterface: TypeToken<MakeInterface>;
  export interface MakeMap {
    readonly $type: "MakeMap";
    readonly reserve: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MakeMap: TypeToken<MakeMap>;
  export interface MakeSlice {
    readonly $type: "MakeSlice";
    readonly len: Value | null;
    readonly cap: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MakeSlice: TypeToken<MakeSlice>;
  export interface MapUpdate {
    readonly $type: "MapUpdate";
    readonly map: Value | null;
    readonly key: Value | null;
    readonly value: Value | null;
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const MapUpdate: TypeToken<MapUpdate>;
  export type Member = Function | Global | NamedConst | Type;
  export interface MultiConvert {
    readonly $type: "MultiConvert";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const MultiConvert: TypeToken<MultiConvert>;
  export const NaiveForm: BuilderMode;
  export interface NamedConst {
    readonly $type: "NamedConst";
    readonly value: Const | null;
    name(): string;
    object(): types.Object | null;
    package(): Package | null;
    pos(): token.Pos;
    relString(from: types.Package | null): string;
    string(): string;
    token(): token.Token;
    type(): types.Type | null;
  }
  export const NamedConst: TypeToken<NamedConst>;
  export function newConst(val: constant.Value | null, typ: types.Type | null): Const | null;
  export function newProgram(fset: token.FileSet | null, mode: BuilderMode): Program | null;
  export interface Next {
    readonly $type: "Next";
    readonly iter: Value | null;
    readonly isString: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Next: TypeToken<Next>;
  export type Node = Alloc | BinOp | Builtin | Call | ChangeInterface | ChangeType | Const | Convert | DebugRef | Defer | Extract | Field | FieldAddr | FreeVar | Function | Global | Go | If | Index | IndexAddr | Jump | Lookup | MakeChan | MakeClosure | MakeInterface | MakeMap | MakeSlice | MapUpdate | MultiConvert | Next | Panic | Parameter | Phi | Range | Return | RunDefers | Select | Send | Slice | SliceToArrayPointer | Store | TypeAssert | UnOp;
  export interface Package {
    readonly $type: "Package";
    readonly prog: Program | null;
    readonly pkg: types.Package | null;
    readonly members: MapView<string, Member | null>;
    build(): void;
    const(name: string): NamedConst | null;
    func(name: string): Function | null;
    setDebugMode(debug: boolean): void;
    string(): string;
    type(name: string): Type | null;
    var(name: string): Global | null;
    writeTo(w: unknown): number;
  }
  export const Package: TypeToken<Package>;
  export interface Panic {
    readonly $type: "Panic";
    readonly x: Value | null;
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const Panic: TypeToken<Panic>;
  export interface Parameter {
    readonly $type: "Parameter";
    name(): string;
    object(): types.Object | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Parameter: TypeToken<Parameter>;
  export interface Phi {
    readonly $type: "Phi";
    readonly comment: string;
    readonly edges: (Value | null)[];
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Phi: TypeToken<Phi>;
  export const PrintFunctions: BuilderMode;
  export const PrintPackages: BuilderMode;
  export interface Program {
    readonly $type: "Program";
    readonly fset: token.FileSet | null;
    readonly methodSets: typeutil.MethodSetCache;
    allPackages(): (Package | null)[];
    build(): void;
    constValue(obj: types.Const | null): Const | null;
    createPackage(pkg: types.Package | null, files: (ast.File | null)[], info: types.Info | null, importable: boolean): Package | null;
    funcValue(obj: types.Func | null): Function | null;
    importedPackage(path: string): Package | null;
    lookupMethod(T: types.Type | null, pkg: types.Package | null, name: string): Function | null;
    methodValue(sel: types.Selection | null): Function | null;
    newFunction(name: string, sig: types.Signature | null, provenance: string): Function | null;
    package(pkg: types.Package | null): Package | null;
    runtimeTypes(): (types.Type | null)[];
    setNoReturn(noReturn: ((arg0: types.Func | null) => boolean) | null): void;
    varValue(obj: types.Var | null, pkg: Package | null, ref: (ast.Node | null | TypeToken<ast.Node>)[]): [Value | null, boolean];
  }
  export const Program: TypeToken<Program>;
  export interface Range {
    readonly $type: "Range";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Range: TypeToken<Range>;
  export interface Return {
    readonly $type: "Return";
    readonly results: (Value | null)[];
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const Return: TypeToken<Return>;
  export interface RunDefers {
    readonly $type: "RunDefers";
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const RunDefers: TypeToken<RunDefers>;
  export const SanityCheckFunctions: BuilderMode;
  export interface Select {
    readonly $type: "Select";
    readonly states: (SelectState | null)[];
    readonly blocking: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Select: TypeToken<Select>;
  export interface SelectState {
    readonly $type: "SelectState";
    readonly dir: types.ChanDir;
    readonly chan: Value | null;
    readonly send: Value | null;
    readonly pos: token.Pos;
    readonly debugNode: ast.Node | null;
  }
  export const SelectState: TypeToken<SelectState>;
  export interface Send {
    readonly $type: "Send";
    readonly chan: Value | null;
    readonly x: Value | null;
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const Send: TypeToken<Send>;
  export interface Slice {
    readonly $type: "Slice";
    readonly x: Value | null;
    readonly low: Value | null;
    readonly high: Value | null;
    readonly max: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const Slice: TypeToken<Slice>;
  export interface SliceToArrayPointer {
    readonly $type: "SliceToArrayPointer";
    readonly x: Value | null;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const SliceToArrayPointer: TypeToken<SliceToArrayPointer>;
  export interface Store {
    readonly $type: "Store";
    readonly addr: Value | null;
    readonly val: Value | null;
    block(): BasicBlock | null;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
  }
  export const Store: TypeToken<Store>;
  export interface Type {
    readonly $type: "Type";
    name(): string;
    object(): types.Object | null;
    package(): Package | null;
    pos(): token.Pos;
    relString(from: types.Package | null): string;
    string(): string;
    token(): token.Token;
    type(): types.Type | null;
  }
  export const Type: TypeToken<Type>;
  export interface TypeAssert {
    readonly $type: "TypeAssert";
    readonly x: Value | null;
    readonly assertedType: types.Type | null;
    readonly commaOk: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const TypeAssert: TypeToken<TypeAssert>;
  export interface UnOp {
    readonly $type: "UnOp";
    readonly op: token.Token;
    readonly x: Value | null;
    readonly commaOk: boolean;
    block(): BasicBlock | null;
    name(): string;
    operands(rands: (Value | null)[]): (Value | null)[];
    parent(): Function | null;
    pos(): token.Pos;
    referrers(): (Instruction | null)[];
    string(): string;
    type(): types.Type | null;
  }
  export const UnOp: TypeToken<UnOp>;
  export type Value = Alloc | BinOp | Builtin | Call | ChangeInterface | ChangeType | Const | Convert | Extract | Field | FieldAddr | FreeVar | Function | Global | Index | IndexAddr | Lookup | MakeChan | MakeClosure | MakeInterface | MakeMap | MakeSlice | MultiConvert | Next | Parameter | Phi | Range | Select | Slice | SliceToArrayPointer | TypeAssert | UnOp;
  export function writeFunction(buf: unknown, f: Function | null): void;
  export function writePackage(buf: unknown, p: Package | null): void;
}
