// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/analysis/passes/buildssa" {
  import type { TypeToken } from "tsk";
  import type * as ssa from "golang.org/x/tools/go/ssa";
  export interface SSA {
    readonly $type: "SSA";
    readonly pkg: ssa.Package | null;
    readonly srcFuncs: (ssa.Function | null)[];
  }
  export const SSA: TypeToken<SSA>;
}
