// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/types/typeutil" {
  import type { TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as types from "go/types";
  export function callee(info: types.Info | null, call: ast.CallExpr | null): types.Object | null;
  export function dependencies(...pkgs: (types.Package | null)[]): (types.Package | null)[];
  export interface Hasher {
    readonly $type: "Hasher";
    hash(t: types.Type | null): number;
  }
  export const Hasher: TypeToken<Hasher>;
  export function intuitiveMethodSet(T: types.Type | null, msets: MethodSetCache | null): (types.Selection | null)[];
  export function makeHasher(): Hasher;
  export interface Map {
    readonly $type: "Map";
    at(key: types.Type | null): unknown;
    delete(key: types.Type | null): boolean;
    iterate(f: ((key: types.Type | null, value: unknown) => void) | null): void;
    keys(): (types.Type | null)[];
    keysString(): string;
    len(): number;
    set(key: types.Type | null, value: unknown): unknown;
    setHasher(arg0: Hasher): void;
    string(): string;
  }
  export const Map: TypeToken<Map>;
  export interface MethodSetCache {
    readonly $type: "MethodSetCache";
    methodSet(T: types.Type | null): types.MethodSet | null;
  }
  export const MethodSetCache: TypeToken<MethodSetCache>;
  export function staticCallee(info: types.Info | null, call: ast.CallExpr | null): types.Func | null;
}
