// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/cfg" {
  import type { TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as token from "go/token";
  export interface Block {
    readonly $type: "Block";
    readonly nodes: (ast.Node | null)[];
    readonly succs: (Block | null)[];
    readonly index: number;
    readonly live: boolean;
    readonly kind: BlockKind;
    readonly stmt: ast.Stmt | null;
    return(): ast.ReturnStmt | null;
    string(): string;
  }
  export const Block: TypeToken<Block>;
  export type BlockKind = number;
  export const BlockKind: {
    string(receiver: BlockKind): string;
  };
  export interface CFG {
    readonly $type: "CFG";
    readonly blocks: (Block | null)[];
    dot(fset: token.FileSet | null): string;
    format(fset: token.FileSet | null): string;
    noReturn(): boolean;
  }
  export const CFG: TypeToken<CFG>;
  export const KindBody: BlockKind;
  export const KindForBody: BlockKind;
  export const KindForDone: BlockKind;
  export const KindForLoop: BlockKind;
  export const KindForPost: BlockKind;
  export const KindIfDone: BlockKind;
  export const KindIfElse: BlockKind;
  export const KindIfThen: BlockKind;
  export const KindInvalid: BlockKind;
  export const KindLabel: BlockKind;
  export const KindRangeBody: BlockKind;
  export const KindRangeDone: BlockKind;
  export const KindRangeLoop: BlockKind;
  export const KindSelectAfterCase: BlockKind;
  export const KindSelectCaseBody: BlockKind;
  export const KindSelectDone: BlockKind;
  export const KindSwitchCaseBody: BlockKind;
  export const KindSwitchDone: BlockKind;
  export const KindSwitchNextCase: BlockKind;
  export const KindUnreachable: BlockKind;
  export function new_(body: ast.BlockStmt | null, mayReturn: ((arg0: ast.CallExpr | null) => boolean) | null): CFG | null;
}
