// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/analysis/passes/buildssa" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as build from "go/build";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as modfile from "golang.org/x/mod/modfile";
  import type * as edge from "golang.org/x/tools/go/ast/edge";
  import type * as inspector from "golang.org/x/tools/go/ast/inspector";
  import type * as ssa from "golang.org/x/tools/go/ssa";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  import type * as fs from "io/fs";
  import type * as os from "os";
  import type * as filepath from "path/filepath";
  export interface SSA {
    readonly $type: "SSA";
    readonly pkg: ssa.Package | null;
    readonly srcFuncs: (ssa.Function | null)[];
  }
  export const SSA: TypeToken<SSA>;
}
