// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/analysis/passes/ctrlflow" {
  import type { TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as types from "go/types";
  import type * as cfg from "golang.org/x/tools/go/cfg";
  export interface CFGs {
    readonly $type: "CFGs";
    funcDecl(decl: ast.FuncDecl | null): cfg.CFG | null;
    funcLit(lit: ast.FuncLit | null): cfg.CFG | null;
    noReturn(fn: types.Func | null): boolean;
  }
  export const CFGs: TypeToken<CFGs>;
}
