// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/tools/go/ast/inspector" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as build from "go/build";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as modfile from "golang.org/x/mod/modfile";
  import type * as buildssa from "golang.org/x/tools/go/analysis/passes/buildssa";
  import type * as edge from "golang.org/x/tools/go/ast/edge";
  import type * as ssa from "golang.org/x/tools/go/ssa";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  import type * as fs from "io/fs";
  import type * as os from "os";
  import type * as filepath from "path/filepath";
  export interface Cursor {
    readonly $type: "Cursor";
    child(n: ast.Node | null): Cursor;
    childAt(k: edge.Kind, idx: number): Cursor;
    children(): GoIterable<Cursor>;
    contains(c2: Cursor): boolean;
    enclosing(...types: (ast.Node | null | TypeToken<ast.Node>)[]): GoIterable<Cursor>;
    findByPos(start: token.Pos, end: token.Pos): Cursor | undefined;
    findNode(n: ast.Node | null): Cursor | undefined;
    firstChild(): Cursor | undefined;
    goString(): string;
    index(): number;
    inspect(types: (ast.Node | null | TypeToken<ast.Node>)[], f: ((c: Cursor) => boolean) | null): void;
    inspector(): Inspector | null;
    lastChild(): Cursor | undefined;
    nextSibling(): Cursor | undefined;
    node(): ast.Node | null;
    parent(): Cursor;
    parentEdge(): [edge.Kind, number];
    parentEdgeIndex(): number;
    parentEdgeKind(): edge.Kind;
    preorder(...types: (ast.Node | null | TypeToken<ast.Node>)[]): GoIterable<Cursor>;
    prevSibling(): Cursor | undefined;
    string(): string;
    valid(): boolean;
  }
  export const Cursor: TypeToken<Cursor>;
  export interface Inspector {
    readonly $type: "Inspector";
    at(index: number): Cursor;
    nodes(types: (ast.Node | null | TypeToken<ast.Node>)[], f: ((n: ast.Node | null, push: boolean) => boolean) | null): void;
    preorder(types: (ast.Node | null | TypeToken<ast.Node>)[], f: ((arg0: ast.Node | null) => void) | null): void;
    preorderSeq(...types: (ast.Node | null | TypeToken<ast.Node>)[]): GoIterable<ast.Node | null>;
    root(): Cursor;
    withStack(types: (ast.Node | null | TypeToken<ast.Node>)[], f: ((n: ast.Node | null, push: boolean, stack: (ast.Node | null)[]) => boolean) | null): void;
  }
  export const Inspector: TypeToken<Inspector>;
  export function new_(files: (ast.File | null)[]): Inspector | null;
}
