// Code generated by tsk-gen. DO NOT EDIT.

declare module "golang.org/x/mod/modfile" {
  import type { GoError, TypeToken } from "tsk";
  export function autoQuote(s: string): string;
  export interface Comment {
    readonly $type: "Comment";
    readonly start: Position;
    readonly token: string;
    readonly suffix: boolean;
  }
  export const Comment: TypeToken<Comment>;
  export interface CommentBlock {
    readonly $type: "CommentBlock";
    readonly comments: Comments;
    readonly start: Position;
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const CommentBlock: TypeToken<CommentBlock>;
  export interface Comments {
    readonly $type: "Comments";
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
  }
  export const Comments: TypeToken<Comments>;
  export class Error extends GoError {
    private constructor();
    readonly $type: "Error";
    readonly filename: string;
    readonly pos: Position;
    readonly verb: string;
    readonly modPath: string;
    readonly err: GoError | null;
    error(): string;
    unwrap(): void;
  }
  export class ErrorList extends GoError {
    private constructor();
    readonly length: number;
    at(index: number): Error;
    [Symbol.iterator](): Iterator<Error>;
    readonly $type: "ErrorList";
    error(): string;
  }
  export interface Exclude {
    readonly $type: "Exclude";
    readonly mod: unknown;
    readonly syntax: Line | null;
  }
  export const Exclude: TypeToken<Exclude>;
  export type Expr = CommentBlock | FileSyntax | LParen | Line | LineBlock | RParen;
  export interface File {
    readonly $type: "File";
    readonly module: Module | null;
    readonly go: Go | null;
    readonly toolchain: Toolchain | null;
    readonly godebug: (Godebug | null)[];
    readonly require: (Require | null)[];
    readonly exclude: (Exclude | null)[];
    readonly replace: (Replace | null)[];
    readonly retract: (Retract | null)[];
    readonly tool: (Tool | null)[];
    readonly ignore: (Ignore | null)[];
    readonly syntax: FileSyntax | null;
    addComment(text: string): void;
    addExclude(path: string, vers: string): void;
    addGoStmt(version: string): void;
    addGodebug(key: string, value: string): void;
    addIgnore(path: string): void;
    addModuleStmt(path: string): void;
    addNewRequire(path: string, vers: string, indirect: boolean): void;
    addReplace(oldPath: string, oldVers: string, newPath: string, newVers: string): void;
    addRequire(path: string, vers: string): void;
    addRetract(vi: VersionInterval, rationale: string): void;
    addTool(path: string): void;
    addToolchainStmt(name: string): void;
    cleanup(): void;
    dropExclude(path: string, vers: string): void;
    dropGoStmt(): void;
    dropGodebug(key: string): void;
    dropIgnore(path: string): void;
    dropReplace(oldPath: string, oldVers: string): void;
    dropRequire(path: string): void;
    dropRetract(vi: VersionInterval): void;
    dropTool(path: string): void;
    dropToolchainStmt(): void;
    format(): string;
    setRequire(req: (Require | null)[]): void;
    setRequireAtMostTwo(req: (Require | null)[]): void;
    setRequireSeparateIndirect(req: (Require | null)[]): void;
    sortBlocks(): void;
  }
  export const File: TypeToken<File>;
  export interface FileSyntax {
    readonly $type: "FileSyntax";
    readonly name: string;
    readonly comments: Comments;
    readonly stmt: (Expr | null)[];
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    cleanup(): void;
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const FileSyntax: TypeToken<FileSyntax>;
  export function format(f: FileSyntax | null): string;
  export interface Go {
    readonly $type: "Go";
    readonly version: string;
    readonly syntax: Line | null;
  }
  export const Go: TypeToken<Go>;
  export const GoVersionRE: unknown;
  export interface Godebug {
    readonly $type: "Godebug";
    readonly key: string;
    readonly value: string;
    readonly syntax: Line | null;
  }
  export const Godebug: TypeToken<Godebug>;
  export interface Ignore {
    readonly $type: "Ignore";
    readonly path: string;
    readonly syntax: Line | null;
  }
  export const Ignore: TypeToken<Ignore>;
  export function isDirectoryPath(ns: string): boolean;
  export interface LParen {
    readonly $type: "LParen";
    readonly comments: Comments;
    readonly pos: Position;
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const LParen: TypeToken<LParen>;
  export interface Line {
    readonly $type: "Line";
    readonly comments: Comments;
    readonly start: Position;
    readonly token: string[];
    readonly inBlock: boolean;
    readonly end: Position;
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const Line: TypeToken<Line>;
  export interface LineBlock {
    readonly $type: "LineBlock";
    readonly comments: Comments;
    readonly start: Position;
    readonly lParen: LParen;
    readonly token: string[];
    readonly line: (Line | null)[];
    readonly rParen: RParen;
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const LineBlock: TypeToken<LineBlock>;
  export interface Module {
    readonly $type: "Module";
    readonly mod: unknown;
    readonly deprecated: string;
    readonly syntax: Line | null;
  }
  export const Module: TypeToken<Module>;
  export function modulePath(mod: string): string;
  export function mustQuote(s: string): boolean;
  export function parse(file: string, data: string, fix: VersionFixer): File | null;
  export function parseLax(file: string, data: string, fix: VersionFixer): File | null;
  export function parseWork(file: string, data: string, fix: VersionFixer): WorkFile | null;
  export interface Position {
    readonly $type: "Position";
    readonly line: number;
    readonly lineRune: number;
    readonly byte: number;
  }
  export const Position: TypeToken<Position>;
  export interface RParen {
    readonly $type: "RParen";
    readonly comments: Comments;
    readonly pos: Position;
    readonly before: Comment[];
    readonly suffix: Comment[];
    readonly after: Comment[];
    comment(): Comments | null;
    span(): [Position, Position];
  }
  export const RParen: TypeToken<RParen>;
  export interface Replace {
    readonly $type: "Replace";
    readonly old: unknown;
    readonly new: unknown;
    readonly syntax: Line | null;
  }
  export const Replace: TypeToken<Replace>;
  export interface Require {
    readonly $type: "Require";
    readonly mod: unknown;
    readonly indirect: boolean;
    readonly syntax: Line | null;
  }
  export const Require: TypeToken<Require>;
  export interface Retract {
    readonly $type: "Retract";
    readonly versionInterval: VersionInterval;
    readonly rationale: string;
    readonly syntax: Line | null;
    readonly low: string;
    readonly high: string;
  }
  export const Retract: TypeToken<Retract>;
  export interface Tool {
    readonly $type: "Tool";
    readonly path: string;
    readonly syntax: Line | null;
  }
  export const Tool: TypeToken<Tool>;
  export interface Toolchain {
    readonly $type: "Toolchain";
    readonly name: string;
    readonly syntax: Line | null;
  }
  export const Toolchain: TypeToken<Toolchain>;
  export const ToolchainRE: unknown;
  export interface Use {
    readonly $type: "Use";
    readonly path: string;
    readonly modulePath: string;
    readonly syntax: Line | null;
  }
  export const Use: TypeToken<Use>;
  export type VersionFixer = ((path: string, version: string) => string) | null;
  export interface VersionInterval {
    readonly $type: "VersionInterval";
    readonly low: string;
    readonly high: string;
  }
  export const VersionInterval: TypeToken<VersionInterval>;
  export interface WorkFile {
    readonly $type: "WorkFile";
    readonly go: Go | null;
    readonly toolchain: Toolchain | null;
    readonly godebug: (Godebug | null)[];
    readonly use: (Use | null)[];
    readonly replace: (Replace | null)[];
    readonly syntax: FileSyntax | null;
    addGoStmt(version: string): void;
    addGodebug(key: string, value: string): void;
    addNewUse(diskPath: string, modulePath: string): void;
    addReplace(oldPath: string, oldVers: string, newPath: string, newVers: string): void;
    addToolchainStmt(name: string): void;
    addUse(diskPath: string, modulePath: string): void;
    cleanup(): void;
    dropGoStmt(): void;
    dropGodebug(key: string): void;
    dropReplace(oldPath: string, oldVers: string): void;
    dropToolchainStmt(): void;
    dropUse(path: string): void;
    setUse(dirs: (Use | null)[]): void;
    sortBlocks(): void;
  }
  export const WorkFile: TypeToken<WorkFile>;
}
