// Code generated by tsk-gen. DO NOT EDIT.

declare module "io/fs" {
  import type { GoError } from "tsk";
  export interface DirEntry {
    readonly $type: string;
    info(): FileInfo | null;
    isDir(): boolean;
    name(): string;
    type(): FileMode;
  }
  export class ErrClosed extends GoError {
    private constructor();
  }
  export class ErrExist extends GoError {
    private constructor();
  }
  export class ErrInvalid extends GoError {
    private constructor();
  }
  export class ErrNotExist extends GoError {
    private constructor();
  }
  export class ErrPermission extends GoError {
    private constructor();
  }
  export interface FS {
    readonly $type: string;
    open(name: string): File | null;
  }
  export interface File {
    readonly $type: string;
    close(): void;
    read(arg0: string): number;
    stat(): FileInfo | null;
  }
  export interface FileInfo {
    readonly $type: string;
    isDir(): boolean;
    modTime(): unknown;
    mode(): FileMode;
    name(): string;
    size(): number;
    sys(): unknown;
  }
  export function fileInfoToDirEntry(info: FileInfo | null): DirEntry | null;
  export type FileMode = number;
  export const FileMode: {
    isDir(receiver: FileMode): boolean;
    isRegular(receiver: FileMode): boolean;
    perm(receiver: FileMode): FileMode;
    string(receiver: FileMode): string;
    type(receiver: FileMode): FileMode;
  };
  export function formatDirEntry(dir: DirEntry | null): string;
  export function formatFileInfo(info: FileInfo | null): string;
  export function glob(fsys: FS | null, pattern: string): string[];
  export interface GlobFS {
    readonly $type: string;
    glob(pattern: string): string[];
    open(name: string): File | null;
  }
  export function lstat(fsys: FS | null, name: string): FileInfo | null;
  export const ModeAppend: FileMode;
  export const ModeCharDevice: FileMode;
  export const ModeDevice: FileMode;
  export const ModeDir: FileMode;
  export const ModeExclusive: FileMode;
  export const ModeIrregular: FileMode;
  export const ModeNamedPipe: FileMode;
  export const ModePerm: FileMode;
  export const ModeSetgid: FileMode;
  export const ModeSetuid: FileMode;
  export const ModeSocket: FileMode;
  export const ModeSticky: FileMode;
  export const ModeSymlink: FileMode;
  export const ModeTemporary: FileMode;
  export const ModeType: FileMode;
  export class PathError extends GoError {
    private constructor();
    readonly $type: "PathError";
    readonly op: string;
    readonly path: string;
    readonly err: GoError | null;
    error(): string;
    timeout(): boolean;
    unwrap(): void;
  }
  export function readDir(fsys: FS | null, name: string): (DirEntry | null)[];
  export interface ReadDirFS {
    readonly $type: string;
    open(name: string): File | null;
    readDir(name: string): (DirEntry | null)[];
  }
  export interface ReadDirFile {
    readonly $type: string;
    close(): void;
    read(arg0: string): number;
    readDir(n: number): (DirEntry | null)[];
    stat(): FileInfo | null;
  }
  export function readFile(fsys: FS | null, name: string): string;
  export interface ReadFileFS {
    readonly $type: string;
    open(name: string): File | null;
    readFile(name: string): string;
  }
  export function readLink(fsys: FS | null, name: string): string;
  export interface ReadLinkFS {
    readonly $type: string;
    lstat(name: string): FileInfo | null;
    open(name: string): File | null;
    readLink(name: string): string;
  }
  export class SkipAll extends GoError {
    private constructor();
  }
  export class SkipDir extends GoError {
    private constructor();
  }
  export function stat(fsys: FS | null, name: string): FileInfo | null;
  export interface StatFS {
    readonly $type: string;
    open(name: string): File | null;
    stat(name: string): FileInfo | null;
  }
  export function sub(fsys: FS | null, dir: string): FS | null;
  export interface SubFS {
    readonly $type: string;
    open(name: string): File | null;
    sub(dir: string): FS | null;
  }
  export function validPath(name: string): boolean;
  export function walkDir(fsys: FS | null, root: string, fn: WalkDirFunc): void;
  export type WalkDirFunc = ((path: string, d: DirEntry | null, err: GoError | null) => void) | null;
}
