// Code generated by tsk-gen. DO NOT EDIT.

declare module "os" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as build from "go/build";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as modfile from "golang.org/x/mod/modfile";
  import type * as edge from "golang.org/x/tools/go/ast/edge";
  import type * as inspector from "golang.org/x/tools/go/ast/inspector";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  import type * as fs from "io/fs";
  import type * as filepath from "path/filepath";
  export type DirEntry = fs.DirEntry | null;
  export class ErrExist extends GoError {
    private constructor();
  }
  export class ErrNotExist extends GoError {
    private constructor();
  }
  export class ErrPermission extends GoError {
    private constructor();
  }
  export type FileInfo = fs.FileInfo | null;
  export type FileMode = fs.FileMode;
  export function getwd(): string;
  export function lstat(name: string): fs.FileInfo | null;
  export function readDir(name: string): (fs.DirEntry | null)[];
  export function readFile(name: string): string;
  export function readlink(name: string): string;
  export function stat(name: string): fs.FileInfo | null;
}
