// Code generated by tsk-gen. DO NOT EDIT.

declare module "os" {
  import type { GoError } from "tsk";
  import type * as fs from "io/fs";
  export type DirEntry = fs.DirEntry | null;
  export class ErrExist extends GoError {
    private constructor();
  }
  export class ErrNotExist extends GoError {
    private constructor();
  }
  export class ErrPermission extends GoError {
    private constructor();
  }
  export type FileInfo = fs.FileInfo | null;
  export type FileMode = fs.FileMode;
  export function getwd(): string;
  export function lstat(name: string): fs.FileInfo | null;
  export function readDir(name: string): (fs.DirEntry | null)[];
  export function readFile(name: string): string;
  export function readlink(name: string): string;
  export function stat(name: string): fs.FileInfo | null;
}
