// Code generated by tsk-gen. DO NOT EDIT.

declare module "path/filepath" {
  import type { GoError, GoIterable, MapView, TypeToken } from "tsk";
  import type * as ast from "go/ast";
  import type * as build from "go/build";
  import type * as constant from "go/constant";
  import type * as token from "go/token";
  import type * as types from "go/types";
  import type * as modfile from "golang.org/x/mod/modfile";
  import type * as buildssa from "golang.org/x/tools/go/analysis/passes/buildssa";
  import type * as edge from "golang.org/x/tools/go/ast/edge";
  import type * as inspector from "golang.org/x/tools/go/ast/inspector";
  import type * as ssa from "golang.org/x/tools/go/ssa";
  import type * as typeutil from "golang.org/x/tools/go/types/typeutil";
  import type * as fs from "io/fs";
  import type * as os from "os";
  export function abs(path: string): string;
  export function base(path: string): string;
  export function clean(path: string): string;
  export function dir(path: string): string;
  export class ErrBadPattern extends GoError {
    private constructor();
  }
  export function evalSymlinks(path: string): string;
  export function ext(path: string): string;
  export function fromSlash(path: string): string;
  export function glob(pattern: string): string[];
  export function hasPrefix(p: string, prefix: string): boolean;
  export function isAbs(path: string): boolean;
  export function isLocal(path: string): boolean;
  export function join(...elem: string[]): string;
  export const ListSeparator: number;
  export function localize(path: string): string;
  export function match(pattern: string, name: string): boolean;
  export function rel(basePath: string, targPath: string): string;
  export const Separator: number;
  export class SkipAll extends GoError {
    private constructor();
  }
  export class SkipDir extends GoError {
    private constructor();
  }
  export function split(path: string): [string, string];
  export function splitList(path: string): string[];
  export function toSlash(path: string): string;
  export function volumeName(path: string): string;
  export function walk(root: string, fn: WalkFunc): void;
  export function walkDir(root: string, fn: fs.WalkDirFunc): void;
  export type WalkFunc = ((path: string, info: fs.FileInfo | null, err: GoError | null) => void) | null;
}
