// Code generated by tsk-gen. DO NOT EDIT.

declare module "path/filepath" {
  import type { GoError } from "tsk";
  export function abs(path: string): string;
  export function base(path: string): string;
  export function clean(path: string): string;
  export function dir(path: string): string;
  export class ErrBadPattern extends GoError {
    private constructor();
  }
  export function evalSymlinks(path: string): string;
  export function ext(path: string): string;
  export function fromSlash(path: string): string;
  export function glob(pattern: string): string[];
  export function hasPrefix(p: string, prefix: string): boolean;
  export function isAbs(path: string): boolean;
  export function isLocal(path: string): boolean;
  export function join(...elem: string[]): string;
  export const ListSeparator: number;
  export function localize(path: string): string;
  export function match(pattern: string, name: string): boolean;
  export function rel(basePath: string, targPath: string): string;
  export const Separator: number;
  export function split(path: string): [string, string];
  export function splitList(path: string): string[];
  export function toSlash(path: string): string;
  export function volumeName(path: string): string;
}
