imports = [
  "github.com/alecthomas/tsk@master//linters",
]

# Lint with the linters in this commit rather than a published version.
replace = { "github.com/alecthomas/tsk//linters" = "../linters" }

# Settings below mirror .golangci.yml.

skip-tests = ["bodyclose", "dupl", "errcheck"]

[errcheck]
check-blank = true

[exhaustive]
check = ["switch", "map"]
