// Package docs renders analyzer documentation as a .tsk/config.toml: each
// analyzer's description, and each config option's default and JSDoc comment.
package docs

import (
	"bytes"
	"io"
	"math"
	"strconv"
	"strings"

	"github.com/alecthomas/errors"
	. "github.com/alecthomas/types/optional"
	ts "github.com/microsoft/TypeScript/tsc/shim/typescript"
	"github.com/pelletier/go-toml/v2"

	"github.com/alecthomas/tsktsk/internal/config"
	"github.com/alecthomas/tsktsk/internal/naming"
)

// Analyzer documents one analyzer.
type Analyzer struct {
	Name string
	Doc  string
	URL  string
	// Source names where the analyzer is defined, such as "builtin" or a
	// script path.
	Source  string
	Enabled bool
	Config  Option[Config]
}

// Config is an analyzer's config type and its defaults, decoded from JSON.
type Config struct {
	Shape    ts.Shape
	Defaults any
}

// TOML writes a .tsk/config.toml with every analyzer's table, its options set
// to their defaults and documented in comments. Arrays of tables are written as
// multi-line inline tables, a TOML 1.1 form, so each field can carry its
// comment. An empty one gets a placeholder entry, so the output is a reference
// to edit rather than a config that loads unchanged. Colour is for terminals
// only: the escapes would corrupt a file.
func TOML(w io.Writer, analyzers []Analyzer, colour bool) error {
	r := newRenderer(colour)
	r.line(r.dim("# Generated by tsk config. Options are set to their defaults. Fill in"))
	r.line(r.dim("# or delete the placeholder entries in empty arrays of tables."))
	if err := r.settings(); err != nil {
		return err
	}
	for _, analyzer := range analyzers {
		r.line("")
		r.line(r.dim("# ") + r.name(analyzer.Name) + r.dim(" (") + r.status(analyzer.Enabled) + r.dim(", ") + r.source(analyzer.Source) + r.dim(")"))
		if analyzer.Doc != "" {
			r.line(r.dim("#"))
			r.indented("# ", analyzer.Doc, r.dim)
		}
		if analyzer.URL != "" {
			r.line(r.dim("# " + analyzer.URL))
		}
		object, ok := configObject(analyzer)
		if !ok {
			r.line(r.dim("#"))
			r.line(r.dim("# No config."))
			continue
		}
		r.line(r.bold("[" + analyzer.Name + "]"))
		config, _ := analyzer.Config.Get()
		if err := r.properties(object, config.Defaults); err != nil {
			return errors.Wrapf(err, "analyzer %s", analyzer.Name)
		}
	}
	return r.writeTo(w)
}

// configObject returns an analyzer's config type when it has options.
func configObject(analyzer Analyzer) (ts.ObjectShape, bool) {
	config, ok := analyzer.Config.Get()
	if !ok {
		return ts.ObjectShape{}, false
	}
	object, isObject := config.Shape.(ts.ObjectShape)
	return object, isObject && len(object.Properties) > 0
}

// renderer accumulates output and colours it with ANSI escapes when enabled.
type renderer struct {
	out    bytes.Buffer
	colour bool
}

func newRenderer(colour bool) *renderer {
	return &renderer{colour: colour}
}

func (r *renderer) writeTo(w io.Writer) error {
	_, err := w.Write(r.out.Bytes())
	return errors.WithStack(err)
}

func (r *renderer) line(text string) {
	r.out.WriteString(text + "\n")
}

// indented writes each line of text after prefix, styled by style.
func (r *renderer) indented(prefix, text string, style func(string) string) {
	if text == "" {
		return
	}
	for line := range strings.SplitSeq(text, "\n") {
		r.line(style(strings.TrimRight(prefix+line, " ")))
	}
}

func (r *renderer) paint(code, text string) string {
	if !r.colour || text == "" {
		return text
	}
	return "\x1b[" + code + "m" + text + "\x1b[0m"
}

func (r *renderer) bold(text string) string   { return r.paint("1", text) }
func (r *renderer) name(text string) string   { return r.paint("1;34", text) }
func (r *renderer) dim(text string) string    { return r.paint("2", text) }
func (r *renderer) key(text string) string    { return r.paint("36", text) }
func (r *renderer) source(text string) string { return r.paint("35", text) }
func (r *renderer) value(text string) string  { return r.paint("32", text) }

func (r *renderer) status(enabled bool) string {
	if enabled {
		return r.paint("32", "enabled")
	}
	return r.paint("31", "disabled")
}

// settings writes the top-level settings, which TOML requires before any
// table.
func (r *renderer) settings() error {
	for _, setting := range config.Settings() {
		rendered, err := encode(setting.Default)
		if err != nil {
			return errors.Wrapf(err, "setting %s", setting.Key)
		}
		r.line("")
		r.indented("# ", setting.Doc, r.dim)
		r.line(r.key(setting.Key) + " = " + r.value(rendered))
	}
	return nil
}

func (r *renderer) properties(object ts.ObjectShape, defaults any) error {
	values, _ := defaults.(map[string]any)
	for i, property := range object.Properties {
		if i > 0 {
			r.line("")
		}
		key, err := naming.Kebab(property.Name)
		if err != nil {
			return errors.WithStack(err)
		}
		r.indented("# ", property.Doc, r.dim)
		value, hasDefault := values[property.Name]
		items, _ := value.([]any)
		element, isTables := arrayOfTables(property.Shape)
		switch {
		case isTables:
			// An empty array shows one placeholder entry so its fields are
			// documented in place; the user fills it in or deletes it.
			if len(items) == 0 {
				items = []any{zeroValue(element)}
			}
			err = r.tables(key, element, items)
		case !hasDefault:
			// An optional option without a default is shown but left unset.
			r.line(r.dim("# " + key + " = <" + typeName(property.Shape) + ">"))
		default:
			var rendered string
			if rendered, err = inlineValue(property.Shape, value); err == nil {
				r.line(r.key(key) + " = " + r.value(rendered))
			}
		}
		if err != nil {
			return err
		}
	}
	return nil
}

// tables writes an array of tables as multi-line inline tables, with each
// field's JSDoc comment above it.
func (r *renderer) tables(key string, element ts.ObjectShape, items []any) error {
	r.line(r.key(key) + " = [{")
	for i, item := range items {
		if i > 0 {
			r.line("}, {")
		}
		values, _ := item.(map[string]any)
		type field struct{ doc, key, value string }
		var fields []field
		for _, property := range element.Properties {
			value, ok := values[property.Name]
			if !ok {
				continue // An optional field the element leaves unset.
			}
			fieldKey, err := naming.Kebab(property.Name)
			if err != nil {
				return errors.WithStack(err)
			}
			rendered, err := inlineValue(property.Shape, value)
			if err != nil {
				return err
			}
			fields = append(fields, field{doc: property.Doc, key: fieldKey, value: rendered})
		}
		for j, f := range fields {
			r.indented("  # ", f.doc, r.dim)
			// TOML separates inline table fields with commas, but none follows
			// the last.
			separator := ","
			if j == len(fields)-1 {
				separator = ""
			}
			r.line("  " + r.key(f.key) + " = " + r.value(f.value) + separator)
		}
	}
	r.line("}]")
	return nil
}

// arrayOfTables returns the element type of an array of objects.
func arrayOfTables(shape ts.Shape) (ts.ObjectShape, bool) {
	array, ok := shape.(ts.ArrayShape)
	if !ok {
		return ts.ObjectShape{}, false
	}
	element, ok := array.Element.(ts.ObjectShape)
	return element, ok
}

// zeroValue is a placeholder value of a shape, in JSON-decoded form, for a
// template.
func zeroValue(shape ts.Shape) any {
	switch shape := shape.(type) {
	case ts.StringShape:
		return ""
	case ts.NumberShape:
		return 0.0
	case ts.BooleanShape:
		return false
	case ts.EnumShape:
		return shape.Values[0]
	case ts.ArrayShape:
		return []any{}
	case ts.ObjectShape:
		values := map[string]any{}
		for _, property := range shape.Properties {
			values[property.Name] = zeroValue(property.Shape)
		}
		return values
	}
	return map[string]any{}
}

func typeName(shape ts.Shape) string {
	switch shape := shape.(type) {
	case ts.StringShape:
		return "string"
	case ts.NumberShape:
		return "number"
	case ts.BooleanShape:
		return "boolean"
	case ts.EnumShape:
		quoted := make([]string, len(shape.Values))
		for i, value := range shape.Values {
			quoted[i] = strconv.Quote(value)
		}
		return "one of " + strings.Join(quoted, ", ")
	case ts.ArrayShape:
		return "array of " + typeName(shape.Element)
	case ts.RecordShape:
		return "table of " + typeName(shape.Element)
	case ts.ObjectShape:
		return "table"
	}
	return "unknown"
}

// inlineValue renders a default as a TOML value. Defaults hold property names,
// so object keys are mapped to their TOML keys first.
func inlineValue(shape ts.Shape, value any) (string, error) {
	converted, err := tomlKeys(shape, value)
	if err != nil {
		return "", err
	}
	return encode(converted)
}

// encode renders a value as an inline TOML value.
func encode(value any) (string, error) {
	var buffer bytes.Buffer
	encoder := toml.NewEncoder(&buffer).SetTablesInline(true)
	if err := encoder.Encode(map[string]any{"v": value}); err != nil {
		return "", errors.Wrap(err, "encode default")
	}
	return strings.TrimSpace(strings.TrimPrefix(buffer.String(), "v = ")), nil
}

// tomlKeys converts a JSON-decoded default to TOML form: object properties to
// kebab-case keys, and whole numbers to integers.
func tomlKeys(shape ts.Shape, value any) (any, error) {
	switch shape := shape.(type) {
	case ts.ObjectShape:
		values, _ := value.(map[string]any)
		converted := make(map[string]any, len(values))
		for _, property := range shape.Properties {
			element, ok := values[property.Name]
			if !ok {
				continue
			}
			key, err := naming.Kebab(property.Name)
			if err != nil {
				return nil, errors.WithStack(err)
			}
			if converted[key], err = tomlKeys(property.Shape, element); err != nil {
				return nil, err
			}
		}
		return converted, nil
	case ts.ArrayShape:
		items, _ := value.([]any)
		converted := make([]any, len(items))
		for i, item := range items {
			var err error
			if converted[i], err = tomlKeys(shape.Element, item); err != nil {
				return nil, err
			}
		}
		return converted, nil
	case ts.RecordShape:
		values, _ := value.(map[string]any)
		converted := make(map[string]any, len(values))
		for key, element := range values {
			var err error
			if converted[key], err = tomlKeys(shape.Element, element); err != nil {
				return nil, err
			}
		}
		return converted, nil
	case ts.NumberShape:
		if number, ok := value.(float64); ok && number == math.Trunc(number) && math.Abs(number) < 1<<53 {
			return int64(number), nil
		}
	}
	return value, nil
}
