package docs_test

import (
	"bytes"
	"regexp"
	"strings"
	"testing"

	"github.com/alecthomas/assert/v2"
	. "github.com/alecthomas/types/optional"
	ts "github.com/microsoft/TypeScript/tsc/shim/typescript"

	"github.com/alecthomas/tsktsk/internal/config"
	"github.com/alecthomas/tsktsk/internal/docs"
)

func shape() ts.ObjectShape {
	rule := ts.ObjectShape{Properties: []ts.Property{
		{Name: "writer", Doc: "Who writes.", Shape: ts.StringShape{}},
		{Name: "maxCount", Shape: ts.NumberShape{}},
	}}
	return ts.ObjectShape{Properties: []ts.Property{
		{Name: "allowReads", Doc: "Rules allowing reads.\nOne per line.", Shape: ts.ArrayShape{Element: rule}},
		{Name: "allowWrites", Doc: "Rules allowing writes.", Shape: ts.ArrayShape{Element: rule}},
		{Name: "mode", Optional: true, Shape: ts.EnumShape{Values: []string{"loose", "strict"}}},
		{Name: "limit", Shape: ts.NumberShape{}},
		{Name: "labels", Shape: ts.RecordShape{Element: ts.StringShape{}}},
	}}
}

func defaults() map[string]any {
	return map[string]any{
		"allowReads": []any{
			map[string]any{"writer": "all", "maxCount": 2.0},
			map[string]any{"writer": "some", "maxCount": 1.0},
		},
		"allowWrites": []any{},
		"limit":       3.0,
		"labels":      map[string]any{"camelKey": "kept"},
	}
}

func analyzers() []docs.Analyzer {
	return []docs.Analyzer{
		{Name: "rules", Doc: "check rules\n\nRules apply to every package.", URL: "https://example.com", Source: "builtin", Enabled: true,
			Config: Some(docs.Config{Shape: shape(), Defaults: defaults()})},
		{Name: "plain", Doc: "no options", Source: ".tsk/plain.ts"},
	}
}

func TestTOML(t *testing.T) {
	var out bytes.Buffer
	assert.NoError(t, docs.TOML(&out, analyzers(), false))
	assert.Equal(t, strings.Join([]string{
		`# Generated by tsk config. Options are set to their defaults. Fill in`,
		`# or delete the placeholder entries in empty arrays of tables.`,
		``,
		`# Analyzers that do not run.`,
		`disable = []`,
		``,
		`# Turn every analyzer off except those listed in enable.`,
		`disable-all = false`,
		``,
		`# Analyzers that run when disable-all is true.`,
		`enable = []`,
		``,
		`# rules (enabled, builtin)`,
		`#`,
		`# check rules`,
		`#`,
		`# Rules apply to every package.`,
		`# https://example.com`,
		`[rules]`,
		`# Rules allowing reads.`,
		`# One per line.`,
		`allow-reads = [{`,
		`  # Who writes.`,
		`  writer = 'all',`,
		`  max-count = 2`,
		`}, {`,
		`  # Who writes.`,
		`  writer = 'some',`,
		`  max-count = 1`,
		`}]`,
		``,
		`# Rules allowing writes.`,
		`allow-writes = [{`,
		`  # Who writes.`,
		`  writer = '',`,
		`  max-count = 0`,
		`}]`,
		``,
		`# mode = <one of "loose", "strict">`,
		``,
		`limit = 3`,
		``,
		`labels = {camelKey = 'kept'}`,
		``,
		`# plain (disabled, .tsk/plain.ts)`,
		`#`,
		`# no options`,
		`#`,
		`# No config.`,
		``,
	}, "\n"), out.String())
}

// Colour only adds ANSI escapes: removing them gives the plain output.
func TestColourOnlyAddsEscapes(t *testing.T) {
	var plain, coloured bytes.Buffer
	assert.NoError(t, docs.TOML(&plain, analyzers(), false))
	assert.NoError(t, docs.TOML(&coloured, analyzers(), true))
	assert.Contains(t, coloured.String(), "\x1b[36mlimit\x1b[0m")
	assert.Contains(t, coloured.String(), "\x1b[1;34mrules\x1b[0m")
	escapes := regexp.MustCompile("\x1b\\[[0-9;]*m")
	assert.Equal(t, plain.String(), escapes.ReplaceAllString(coloured.String(), ""))
}

// The output is a reference with placeholder entries, so it need not keep the
// defaults, but it must still be TOML the config loader can read and match
// against the config type.
func TestTOMLParses(t *testing.T) {
	var out bytes.Buffer
	assert.NoError(t, docs.TOML(&out, analyzers(), false))
	file, err := config.Parse("generated.toml", out.String())
	assert.NoError(t, err)
	_, err = config.Resolve("rules", shape(), nil, file.Tables["rules"])
	assert.NoError(t, err)
}
