//go:build ignore

// Command gen writes pool_gen.go.
package main

import (
	"fmt"
	"os"
	"strings"
)

const size = 256

func main() {
	var out strings.Builder
	out.WriteString("// Code generated by gen.go. DO NOT EDIT.\n\npackage facts\n\n")
	for i := range size {
		fmt.Fprintf(&out, "type fact%03d struct{ Payload }\n", i)
	}
	out.WriteString("\nfunc pool() []Fact {\n\treturn []Fact{\n")
	for i := range size {
		fmt.Fprintf(&out, "\t\tnew(fact%03d),\n", i)
	}
	out.WriteString("\t}\n}\n")
	if err := os.WriteFile("pool_gen.go", []byte(out.String()), 0o600); err != nil {
		panic(err)
	}
}
