// Code generated by gen.go. DO NOT EDIT.

package facts

type fact000 struct{ Payload }
type fact001 struct{ Payload }
type fact002 struct{ Payload }
type fact003 struct{ Payload }
type fact004 struct{ Payload }
type fact005 struct{ Payload }
type fact006 struct{ Payload }
type fact007 struct{ Payload }
type fact008 struct{ Payload }
type fact009 struct{ Payload }
type fact010 struct{ Payload }
type fact011 struct{ Payload }
type fact012 struct{ Payload }
type fact013 struct{ Payload }
type fact014 struct{ Payload }
type fact015 struct{ Payload }
type fact016 struct{ Payload }
type fact017 struct{ Payload }
type fact018 struct{ Payload }
type fact019 struct{ Payload }
type fact020 struct{ Payload }
type fact021 struct{ Payload }
type fact022 struct{ Payload }
type fact023 struct{ Payload }
type fact024 struct{ Payload }
type fact025 struct{ Payload }
type fact026 struct{ Payload }
type fact027 struct{ Payload }
type fact028 struct{ Payload }
type fact029 struct{ Payload }
type fact030 struct{ Payload }
type fact031 struct{ Payload }
type fact032 struct{ Payload }
type fact033 struct{ Payload }
type fact034 struct{ Payload }
type fact035 struct{ Payload }
type fact036 struct{ Payload }
type fact037 struct{ Payload }
type fact038 struct{ Payload }
type fact039 struct{ Payload }
type fact040 struct{ Payload }
type fact041 struct{ Payload }
type fact042 struct{ Payload }
type fact043 struct{ Payload }
type fact044 struct{ Payload }
type fact045 struct{ Payload }
type fact046 struct{ Payload }
type fact047 struct{ Payload }
type fact048 struct{ Payload }
type fact049 struct{ Payload }
type fact050 struct{ Payload }
type fact051 struct{ Payload }
type fact052 struct{ Payload }
type fact053 struct{ Payload }
type fact054 struct{ Payload }
type fact055 struct{ Payload }
type fact056 struct{ Payload }
type fact057 struct{ Payload }
type fact058 struct{ Payload }
type fact059 struct{ Payload }
type fact060 struct{ Payload }
type fact061 struct{ Payload }
type fact062 struct{ Payload }
type fact063 struct{ Payload }
type fact064 struct{ Payload }
type fact065 struct{ Payload }
type fact066 struct{ Payload }
type fact067 struct{ Payload }
type fact068 struct{ Payload }
type fact069 struct{ Payload }
type fact070 struct{ Payload }
type fact071 struct{ Payload }
type fact072 struct{ Payload }
type fact073 struct{ Payload }
type fact074 struct{ Payload }
type fact075 struct{ Payload }
type fact076 struct{ Payload }
type fact077 struct{ Payload }
type fact078 struct{ Payload }
type fact079 struct{ Payload }
type fact080 struct{ Payload }
type fact081 struct{ Payload }
type fact082 struct{ Payload }
type fact083 struct{ Payload }
type fact084 struct{ Payload }
type fact085 struct{ Payload }
type fact086 struct{ Payload }
type fact087 struct{ Payload }
type fact088 struct{ Payload }
type fact089 struct{ Payload }
type fact090 struct{ Payload }
type fact091 struct{ Payload }
type fact092 struct{ Payload }
type fact093 struct{ Payload }
type fact094 struct{ Payload }
type fact095 struct{ Payload }
type fact096 struct{ Payload }
type fact097 struct{ Payload }
type fact098 struct{ Payload }
type fact099 struct{ Payload }
type fact100 struct{ Payload }
type fact101 struct{ Payload }
type fact102 struct{ Payload }
type fact103 struct{ Payload }
type fact104 struct{ Payload }
type fact105 struct{ Payload }
type fact106 struct{ Payload }
type fact107 struct{ Payload }
type fact108 struct{ Payload }
type fact109 struct{ Payload }
type fact110 struct{ Payload }
type fact111 struct{ Payload }
type fact112 struct{ Payload }
type fact113 struct{ Payload }
type fact114 struct{ Payload }
type fact115 struct{ Payload }
type fact116 struct{ Payload }
type fact117 struct{ Payload }
type fact118 struct{ Payload }
type fact119 struct{ Payload }
type fact120 struct{ Payload }
type fact121 struct{ Payload }
type fact122 struct{ Payload }
type fact123 struct{ Payload }
type fact124 struct{ Payload }
type fact125 struct{ Payload }
type fact126 struct{ Payload }
type fact127 struct{ Payload }
type fact128 struct{ Payload }
type fact129 struct{ Payload }
type fact130 struct{ Payload }
type fact131 struct{ Payload }
type fact132 struct{ Payload }
type fact133 struct{ Payload }
type fact134 struct{ Payload }
type fact135 struct{ Payload }
type fact136 struct{ Payload }
type fact137 struct{ Payload }
type fact138 struct{ Payload }
type fact139 struct{ Payload }
type fact140 struct{ Payload }
type fact141 struct{ Payload }
type fact142 struct{ Payload }
type fact143 struct{ Payload }
type fact144 struct{ Payload }
type fact145 struct{ Payload }
type fact146 struct{ Payload }
type fact147 struct{ Payload }
type fact148 struct{ Payload }
type fact149 struct{ Payload }
type fact150 struct{ Payload }
type fact151 struct{ Payload }
type fact152 struct{ Payload }
type fact153 struct{ Payload }
type fact154 struct{ Payload }
type fact155 struct{ Payload }
type fact156 struct{ Payload }
type fact157 struct{ Payload }
type fact158 struct{ Payload }
type fact159 struct{ Payload }
type fact160 struct{ Payload }
type fact161 struct{ Payload }
type fact162 struct{ Payload }
type fact163 struct{ Payload }
type fact164 struct{ Payload }
type fact165 struct{ Payload }
type fact166 struct{ Payload }
type fact167 struct{ Payload }
type fact168 struct{ Payload }
type fact169 struct{ Payload }
type fact170 struct{ Payload }
type fact171 struct{ Payload }
type fact172 struct{ Payload }
type fact173 struct{ Payload }
type fact174 struct{ Payload }
type fact175 struct{ Payload }
type fact176 struct{ Payload }
type fact177 struct{ Payload }
type fact178 struct{ Payload }
type fact179 struct{ Payload }
type fact180 struct{ Payload }
type fact181 struct{ Payload }
type fact182 struct{ Payload }
type fact183 struct{ Payload }
type fact184 struct{ Payload }
type fact185 struct{ Payload }
type fact186 struct{ Payload }
type fact187 struct{ Payload }
type fact188 struct{ Payload }
type fact189 struct{ Payload }
type fact190 struct{ Payload }
type fact191 struct{ Payload }
type fact192 struct{ Payload }
type fact193 struct{ Payload }
type fact194 struct{ Payload }
type fact195 struct{ Payload }
type fact196 struct{ Payload }
type fact197 struct{ Payload }
type fact198 struct{ Payload }
type fact199 struct{ Payload }
type fact200 struct{ Payload }
type fact201 struct{ Payload }
type fact202 struct{ Payload }
type fact203 struct{ Payload }
type fact204 struct{ Payload }
type fact205 struct{ Payload }
type fact206 struct{ Payload }
type fact207 struct{ Payload }
type fact208 struct{ Payload }
type fact209 struct{ Payload }
type fact210 struct{ Payload }
type fact211 struct{ Payload }
type fact212 struct{ Payload }
type fact213 struct{ Payload }
type fact214 struct{ Payload }
type fact215 struct{ Payload }
type fact216 struct{ Payload }
type fact217 struct{ Payload }
type fact218 struct{ Payload }
type fact219 struct{ Payload }
type fact220 struct{ Payload }
type fact221 struct{ Payload }
type fact222 struct{ Payload }
type fact223 struct{ Payload }
type fact224 struct{ Payload }
type fact225 struct{ Payload }
type fact226 struct{ Payload }
type fact227 struct{ Payload }
type fact228 struct{ Payload }
type fact229 struct{ Payload }
type fact230 struct{ Payload }
type fact231 struct{ Payload }
type fact232 struct{ Payload }
type fact233 struct{ Payload }
type fact234 struct{ Payload }
type fact235 struct{ Payload }
type fact236 struct{ Payload }
type fact237 struct{ Payload }
type fact238 struct{ Payload }
type fact239 struct{ Payload }
type fact240 struct{ Payload }
type fact241 struct{ Payload }
type fact242 struct{ Payload }
type fact243 struct{ Payload }
type fact244 struct{ Payload }
type fact245 struct{ Payload }
type fact246 struct{ Payload }
type fact247 struct{ Payload }
type fact248 struct{ Payload }
type fact249 struct{ Payload }
type fact250 struct{ Payload }
type fact251 struct{ Payload }
type fact252 struct{ Payload }
type fact253 struct{ Payload }
type fact254 struct{ Payload }
type fact255 struct{ Payload }

func pool() []Fact {
	return []Fact{
		new(fact000),
		new(fact001),
		new(fact002),
		new(fact003),
		new(fact004),
		new(fact005),
		new(fact006),
		new(fact007),
		new(fact008),
		new(fact009),
		new(fact010),
		new(fact011),
		new(fact012),
		new(fact013),
		new(fact014),
		new(fact015),
		new(fact016),
		new(fact017),
		new(fact018),
		new(fact019),
		new(fact020),
		new(fact021),
		new(fact022),
		new(fact023),
		new(fact024),
		new(fact025),
		new(fact026),
		new(fact027),
		new(fact028),
		new(fact029),
		new(fact030),
		new(fact031),
		new(fact032),
		new(fact033),
		new(fact034),
		new(fact035),
		new(fact036),
		new(fact037),
		new(fact038),
		new(fact039),
		new(fact040),
		new(fact041),
		new(fact042),
		new(fact043),
		new(fact044),
		new(fact045),
		new(fact046),
		new(fact047),
		new(fact048),
		new(fact049),
		new(fact050),
		new(fact051),
		new(fact052),
		new(fact053),
		new(fact054),
		new(fact055),
		new(fact056),
		new(fact057),
		new(fact058),
		new(fact059),
		new(fact060),
		new(fact061),
		new(fact062),
		new(fact063),
		new(fact064),
		new(fact065),
		new(fact066),
		new(fact067),
		new(fact068),
		new(fact069),
		new(fact070),
		new(fact071),
		new(fact072),
		new(fact073),
		new(fact074),
		new(fact075),
		new(fact076),
		new(fact077),
		new(fact078),
		new(fact079),
		new(fact080),
		new(fact081),
		new(fact082),
		new(fact083),
		new(fact084),
		new(fact085),
		new(fact086),
		new(fact087),
		new(fact088),
		new(fact089),
		new(fact090),
		new(fact091),
		new(fact092),
		new(fact093),
		new(fact094),
		new(fact095),
		new(fact096),
		new(fact097),
		new(fact098),
		new(fact099),
		new(fact100),
		new(fact101),
		new(fact102),
		new(fact103),
		new(fact104),
		new(fact105),
		new(fact106),
		new(fact107),
		new(fact108),
		new(fact109),
		new(fact110),
		new(fact111),
		new(fact112),
		new(fact113),
		new(fact114),
		new(fact115),
		new(fact116),
		new(fact117),
		new(fact118),
		new(fact119),
		new(fact120),
		new(fact121),
		new(fact122),
		new(fact123),
		new(fact124),
		new(fact125),
		new(fact126),
		new(fact127),
		new(fact128),
		new(fact129),
		new(fact130),
		new(fact131),
		new(fact132),
		new(fact133),
		new(fact134),
		new(fact135),
		new(fact136),
		new(fact137),
		new(fact138),
		new(fact139),
		new(fact140),
		new(fact141),
		new(fact142),
		new(fact143),
		new(fact144),
		new(fact145),
		new(fact146),
		new(fact147),
		new(fact148),
		new(fact149),
		new(fact150),
		new(fact151),
		new(fact152),
		new(fact153),
		new(fact154),
		new(fact155),
		new(fact156),
		new(fact157),
		new(fact158),
		new(fact159),
		new(fact160),
		new(fact161),
		new(fact162),
		new(fact163),
		new(fact164),
		new(fact165),
		new(fact166),
		new(fact167),
		new(fact168),
		new(fact169),
		new(fact170),
		new(fact171),
		new(fact172),
		new(fact173),
		new(fact174),
		new(fact175),
		new(fact176),
		new(fact177),
		new(fact178),
		new(fact179),
		new(fact180),
		new(fact181),
		new(fact182),
		new(fact183),
		new(fact184),
		new(fact185),
		new(fact186),
		new(fact187),
		new(fact188),
		new(fact189),
		new(fact190),
		new(fact191),
		new(fact192),
		new(fact193),
		new(fact194),
		new(fact195),
		new(fact196),
		new(fact197),
		new(fact198),
		new(fact199),
		new(fact200),
		new(fact201),
		new(fact202),
		new(fact203),
		new(fact204),
		new(fact205),
		new(fact206),
		new(fact207),
		new(fact208),
		new(fact209),
		new(fact210),
		new(fact211),
		new(fact212),
		new(fact213),
		new(fact214),
		new(fact215),
		new(fact216),
		new(fact217),
		new(fact218),
		new(fact219),
		new(fact220),
		new(fact221),
		new(fact222),
		new(fact223),
		new(fact224),
		new(fact225),
		new(fact226),
		new(fact227),
		new(fact228),
		new(fact229),
		new(fact230),
		new(fact231),
		new(fact232),
		new(fact233),
		new(fact234),
		new(fact235),
		new(fact236),
		new(fact237),
		new(fact238),
		new(fact239),
		new(fact240),
		new(fact241),
		new(fact242),
		new(fact243),
		new(fact244),
		new(fact245),
		new(fact246),
		new(fact247),
		new(fact248),
		new(fact249),
		new(fact250),
		new(fact251),
		new(fact252),
		new(fact253),
		new(fact254),
		new(fact255),
	}
}
